### ISSUE TITLE
cdkworkshop.com not updating

### ISSUE THREAD

**Issue by kylelaker** [aws-samples/aws-cdk-intro-workshop#100]
### What is the problem?

The https://cdkworkshop.com site is not updating. It does not match the contents of this repo. This is especially notable with the Python examples which remain incorrect and out of date (fixed in #99). Is the site not being rebuilt/updated?

### Reproduction Steps

Visit https://cdkworkshop.com/40-dotnet/30-hello-cdk/300-apigw.html which should have the fix from 055f5c4d61d3c8180b13e2b5eb2edc1f17129869 (#97) on the page. It does not. 

Visit https://cdkworkshop.com/30-python/20-create-project/300-structure.html which should have the fixes from #99 on the page. It does not.

### Environment

  - **CDK CLI Version:** 
  - **Section:** 
  - **Browser:** 
  - **Language:**

**Comment by NGL321** [comment]
Hey @kylelaker,

Thank you for the report!
Unfortunately, there is sometimes some delay between fixes being pushed and the site updating. We are trying to keep that time limited to a week (have weekly deployments of the workshop), but the timeframes are still a discussion.
The workshop is up to date for now.

If you think you catch anything else, please dont hesitate to report.
Thank you again!

😸
