### ISSUE TITLE
Inconsistency in project naming - Python path

### ISSUE THREAD

**Issue by rajish** [aws-samples/aws-cdk-intro-workshop#102]
### What is the problem?
The project name set in the `cdk init` step is `cdkworkshop` while in other parts in text it's referred as `hello` or `HelloWorld` which causes confusion.

### Environment

  - **CDK CLI Version:** 1.19.0 (build 5597bbe)
  - **Section:** all
  - **Browser:** Chrome
  - **Language:** Python

**Comment by NGL321** [comment]
Thank you for the report!

I have verified the problem, and will work on pushing a fix shortly!

😸
