### ISSUE TITLE
Cognito user pool + APIGW + Lambdas

### ISSUE THREAD

**Issue by ximarin** [aws-samples/aws-cdk-intro-workshop#103]
### The Question
Is it possible to get a step by step example for how to set up an APIGW so it uses specific Cognito user pools for specific URLs?

Similar to [this question on stackoverflow](https://stackoverflow.com/questions/59489587/aws-cdk-tie-cognito-user-pool-to-api-gateway).

### Environment

  - **CDK CLI Version:** 1.19.0 (build 5597bbe)
  - **Section:** n/a
  - **Browser:** all
  - **Language:** all | Python

### Other information 
The idea is to have a working set of Cognito user pools.
These should then be used as Authorizers for a set of API GW Rest APIs that trigger lambdas.
The example should explain how to create the authorizers properly.
The example should also explain how to make use of the tokens within lambda.

**Comment by NGL321** [comment]
Hi @ximarin,

Sorry for the delay, I think this is better suited [here](https://github.com/aws-samples/aws-cdk-examples) for the sake of expediency, I have made an [issue](https://github.com/aws-samples/aws-cdk-examples/issues/244) for you there, and am going to close this issue.

😸
