### ISSUE TITLE
Add Testing Section to the Workshop

### ISSUE THREAD

**Issue by evgenyka** [aws-samples/aws-cdk-intro-workshop#1048]
### General Information

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

Add a dedicated 'testing' section to the workshop.

### Proposed Solution

Adding dedicated Testing section, which will focus on practical exercises and strategies to test CDK applications. By incorporating testing, participants will gain hands-on experience in validating their CDK project and identifying areas for improvement. The 'testing' section will enable participants to develop a comprehensive understanding of how to evaluate their CDK project, ensuring they meet the desired objectives and deliver optimal results

### Section

Testing

### Browser

all

### Language

all

**Comment by ashishdhingra** [comment]
Thanks for raising the feature request.
