### ISSUE TITLE
Add a workshop lab Integration Testing using @aws-cdk/integ-tests-alpha

### ISSUE THREAD

**Issue by sfwhite** [aws-samples/aws-cdk-intro-workshop#1050]
### General Information

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

The @aws-cdk/integ-tests-alpha package is extremely valuable for ci/cd systems. 
It would be valuable to have a lab to showcase this feature.

### Proposed Solution

Please expand the Testing Constructs section to include a lab for building and executing an Integration Test for a given construct.

### Section

Advanced Topics/Testing Constructs

### Browser

all

### Language

all

### Other information

https://docs.aws.amazon.com/cdk/api/v2/docs/integ-tests-alpha-readme.html

**Comment by ashishdhingra** [comment]
@sfwhite Thanks for opening feature request. On https://docs.aws.amazon.com/cdk/api/v2/docs/integ-tests-alpha-readme.html, I see below note;
```
The APIs of higher level constructs in this module are experimental and under active development. They are subject to non-backward compatible changes or removal in any future version. These are not subject to the [Semantic Versioning](https://semver.org/) model and breaking changes will be announced in the release notes. This means that while you may use them, you may need to update your source code when upgrading to a newer version of this package.
```
Given the API is experimental, it would not be scalable to add this to CDK workshop as of now.

Thanks,
Ashish
