### ISSUE TITLE
Add a lab to Advanced Topics for Aspects

### ISSUE THREAD

**Issue by sfwhite** [aws-samples/aws-cdk-intro-workshop#1051]
### General Information

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

Aspects are a powerful feature for custom corrective actions, and an important feature for CDKv2 from an enterprise adoption angle. You should draw attention to this feature as an Advanced Topic within the workshop.

### Proposed Solution

Create an Advanced Topics/Compliance section.
Add a guide for Aspects to this new section.

### Section

Advanced Topics/Compliance/Aspects

### Browser

all

### Language

all

### Other information

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Aspects.html

**Comment by ashishdhingra** [comment]
Thanks for creating feature request.
