### ISSUE TITLE
CDK Deploy fails due to nodejs12.x dependency in cdk-dynamo-table-viewer

### ISSUE THREAD

**Issue by ttarabbia** [aws-samples/aws-cdk-intro-workshop#1060]
### Describe the bug

CDK Deploy fails on this step: https://cdkworkshop.com/20-typescript/50-table-viewer/500-deploy.html.
This is due to setting the library version to `npm install cdk-dynamo-table-viewer@0.2.0`

### Expected Behavior

Expected CDK deploy to just deploy

### Current Behavior

Error is ```Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions.```

### Reproduction Steps

Install 0.2.0 version of cdk-dynamo-table-viewer and walk through workshop.
https://cdkworkshop.com/20-typescript/50-table-viewer/200-install.html

### Possible Solution

When I run just `npm install cdk-dynamo-table-viewer` instead of version lock to 0.2.0 then cdk deploy works. 

### CDK CLI Version

2.82.0 (build 3a8648a)

### Section

Using construct libraries

### Language

TypeScript

**Comment by arditti** [comment]
Just faces the same issue, and created a PR for fixing it:
https://github.com/aws-samples/aws-cdk-intro-workshop/pull/1061
