### ISSUE TITLE
In TypeScript project, 'noUnusedLocals' is not enabled

### ISSUE THREAD

**Issue by fshields** [aws-samples/aws-cdk-intro-workshop#108]
### What is the problem?
https://github.com/aws-samples/aws-cdk-intro-workshop/blob/master/workshop/content/20-typescript/30-hello-cdk/200-lambda.md states the following:
> Once you save cdk-workshop-stack.ts, you should see an error message in the npm run watch window that hello is declared but never use. Cool huh?

However, you will not receive that error message because the in the `tsconfig.json` that is shipped with the project, the `noUnusedLocals` `compilerOptions` are set to `false`.

This is very confusing for people executing the tutorial because they are told that they will be receiving output that they do not.

### Reproduction Steps
Execute the TypeScript project, exactly as stated, up through the "Add an AWS Lambda Function to your stack" section of [ AWS CDK Intro Workshop > TypeScript Workshop > Hello, CDK! > Hello Lambda ]

### Environment

  - **CDK CLI Version:** 
  - **Section:** [ AWS CDK Intro Workshop > TypeScript Workshop > Hello, CDK! > Hello Lambda ]
  - **Browser:** Chrome
  - **Language:** TypeScript

### Other information 
To fix this inconsistency, either:
1. Set  `noUnusedLocals` to `true` in the `compilerOptions` section of `tsconfig.json`
2. or Remove the statement in the tutorial that claims you will receive the error message about unused variables.

**Comment by fshields** [comment]
If you choose to _not_ update `noUnusedLocals` to `true`, then you should also delete the statement:
> Oops, an error! No worries, we’ll be using props shortly.

from https://github.com/aws-samples/aws-cdk-intro-workshop/blob/master/workshop/content/20-typescript/40-hit-counter/100-api.md

**Comment by NGL321** [comment]
Sorry for the delay. It looks like this was already reported in #92 and resolved in #117
