### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by julianbonilla** [aws-samples/aws-cdk-intro-workshop#1101]
### General Information

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

Spanish translation of the CDK Workshop.

Contributors: @julianbonilla, @danno-s, @juanb3r, @ssaanncchheezz, @gealvarado.

### Proposed Solution

The Spanish content will be added to `workshop/content/spanish` following the same pattern in #601.

Work in progress: https://github.com/aws-samples/aws-cdk-intro-workshop/compare/master...julianbonilla:aws-cdk-intro-workshop:es-lang-support

### Language

Spanish

**Comment by chunkjs** [comment]
@julianbonilla hello ☺️ I am looking to help out, noticed this is tagged with an "effort/large" label, wondering if you needed help. I am a native Spanish speaking software engineer, please let me know!
