### ISSUE TITLE
docs: Move TypeScript stop 'watch' to cleanup steps

### ISSUE THREAD

**Issue by fshields** [aws-samples/aws-cdk-intro-workshop#112]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description
In the workshop documentation for the TypeScript project, the user is told to stop the `npm run watch` command after completing /workshop/content/20-typescript/50-table-viewer/400-expose-table.md.  However, this makes it impossible to complete the "Extra credit" two steps later because changes to the TypeScript files will not be converted to their JavaScript version.

Stopping the `watch` should be part of the Clean Up operations at the end of the workshop.

### Proposed Solution
Move the phrase:
> We’re finished making code changes, so once you save this file, you can close the npm run watch command with Ctrl-C.

from /workshop/content/20-typescript/50-table-viewer/400-expose-table.md
to /workshop/content/20-typescript/60-cleanups.md

### Environment

  - **CDK CLI Version:** 1.19.0 (build 5597bbe)
  - **Section:** [ AWS CDK Intro Workshop > TypeScript Workshop > Using construct libraries > Exposing our hit counter table ]
  - **Browser:** Chrome
  - **Language:** TypeScript

**Comment by peterwoodworth** [comment]
Might want to remove watch altogether
