### ISSUE TITLE
Node Runtime not supported anymore

### ISSUE THREAD

**Issue by pankaj200788** [aws-samples/aws-cdk-intro-workshop#113]
### What is the problem?

Node runtime_8_10 is not supported by Lambda anymore. Please update the same in the workshop.

### Verbose Log

    const hello = new lambda.Function(this, 'HelloHandler', {
      runtime: lambda.Runtime.NODEJS_8_10,      // execution environment
      code: lambda.Code.asset('lambda'),  // code loaded from the "lambda" directory
      handler: 'hello.handler' 

https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html
-->

### Environment

  - **CDK CLI Version:** 1.20.0
  - **Section:**  Hello Lambda
  - **Browser:** all
  - **Language:** Typescript

**Comment by NGL321** [comment]
Resolved by #118
