### ISSUE TITLE
Not all languages have a "deploy" before "destroy" step

### ISSUE THREAD

**Issue by mobob** [aws-samples/aws-cdk-intro-workshop#1131]
### Describe the bug

Before the cdk destroy step, if you don't deploy your dynamo db doesn't get cleaned up.

### Expected Behavior

The docs should at least suggest deploying before destroying.

### Current Behavior

Deploy is not suggested.

### Reproduction Steps

Read the docs.

### Possible Solution

Update the docs to suggest deploy before destroy.

**Comment by mobob** [comment]
FYI i did submit a PR for this: https://github.com/aws-samples/aws-cdk-intro-workshop/pull/1132

**Comment by ashishdhingra** [comment]
> FYI i did submit a PR for this: #1132

@mobob Thanks for the PR. We will review and merge it.

**Comment by ashishdhingra** [comment]
PR merged.
