### ISSUE TITLE
Use new `TableV2` construct

### ISSUE THREAD

**Issue by scanlonp** [aws-samples/aws-cdk-intro-workshop#1178]
### General Information

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

We recently introduced dynamo `TableV2`. Update the table in hit counter to the new construct.

This could be added to #1170.

### Proposed Solution

Update cdk-lib version; change construct.

**Comment by ashishdhingra** [comment]
@scanlonp Thanks for the feature request. Feel free to contribute PR that makes changes:
- To all language workshops.
- Both English and Japanese versions.
- Please ensure that all examples work.

Thanks,
Ashish
