### ISSUE TITLE
Inconsistent use of `cdk (command)` and `npx cdk (command)`

### ISSUE THREAD

**Issue by scanlonp** [aws-samples/aws-cdk-intro-workshop#1188]
### Describe the bug

In the pipelines workshop, deploy commands are done by `npx cdk deploy`. In all sections leading up to this, they are `cdk deploy`. This should not affect the behavior of the code, but is inconsistent.

I can open a pull for this.

### Expected Behavior

Standardized CLI commands.

### Current Behavior

Mix of CLI commands.

### Reproduction Steps

[This page](https://cdkworkshop.com/20-typescript/20-create-project/500-deploy.html)
vs
[this page](https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/2000-create-repo.html)

### Language

Typescript

**Comment by ashishdhingra** [comment]
@scanlonp Thanks for pointing the inconsistency. Feel free to contribute PR with a fix. Please ensure the following:
- Make the changes for all language workshops, for both English and Japanese languages
- Ensure locally that omitting `npx` works.

Thanks,
Ashish

**Comment by stefanfreitag** [comment]
@scanlonp @ashishdhingra  I have some capacity left and if you both are fine, I can look into this.
