### ISSUE TITLE
Prereq Instructions for IAM out-of-date

### ISSUE THREAD

**Issue by voluntary-hardship** [aws-samples/aws-cdk-intro-workshop#1216]
### Describe the bug

https://cdkworkshop.com/15-prerequisites/200-account.html#administrator-user
Administrator User Instructions to set up Programmatic Access are out-of-date with the new AWS Console experience. 

### Expected Behavior

Create the IAM user first, then after creation choose from several access key options. 

### Current Behavior

Go to the AWS IAM console and [create a new user](https://console.aws.amazon.com/iam/home?#/users$new).
Type a name for your user (e.g. cdk-workshop) and choose “Programmatic access”.

### Reproduction Steps

https://cdkworkshop.com/15-prerequisites/200-account.html#administrator-user

### Possible Solution

Modify instructions to match the new console experience: 
Create the IAM user first, then after creation choose from several access key options. 

### Section

prerequisites 200-account.html administrator-user

### Browser

Chrome

### Language

All

**Comment by ashishdhingra** [comment]
Thanks for reporting the issue. We will roll out a fix soon.
