### ISSUE TITLE
cdk-dynamo-table-view version 0.20 uses an unsupported NodeJS version (version 12)

### ISSUE THREAD

**Issue by silver-mx** [aws-samples/aws-cdk-intro-workshop#1231]
### Describe the bug

The section about using construct libraries (see [page](https://cdkworkshop.com/50-java/50-table-viewer/200-install.html)) uses the following construct dependency:

```
        <!-- Additional Construct Libraries -->
        <dependency>
            <groupId>io.github.cdklabs</groupId>
            <artifactId>cdk-dynamo-table-view</artifactId>
            <version>0.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId> software.amazon.jsii</groupId>
                    <artifactId>jsii-runtime</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

The version `0.2.0` in this case uses NodeJS 12, which is already unsupported by AWS, and therefore the deployment for the section fails.

### Expected Behavior

The deployment for the given section must succeed.

### Current Behavior

The deployment for the given section fails.

### Reproduction Steps

See description.

### Possible Solution

Bump the version to ` 0.2.487` available at https://central.sonatype.com/artifact/io.github.cdklabs/cdk-dynamo-table-view.

### CDK CLI Version

2.103.1 (build 3bb19ac)

### Section

Using construct libraries

### Language

Java

**Comment by hatted** [comment]
Python version also has the same issue.   [https://cdkworkshop.com/30-python/50-table-viewer/500-deploy.html#cdk-deploy](url)

`
7:39:03 AM | CREATE_FAILED        | AWS::Lambda::Function       | ViewHitCounterRendered9C783E45
Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use t
he new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: fc313d0f-2bc3-4a4c-8c4d-bf1a0c796c50)" (RequestTok
en: ed5bbfbd-9f98-84bd-c5b0-49b2a88ad719, HandlerErrorCode: InvalidRequest)


 ❌  CdkWorkshopStack failed: Error: The stack named CdkWorkshopStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: fc313d0f-2bc3-4a4c-8c4d-bf1a0c796c50)" (RequestToken: ed5bbfbd-9f98-84bd-c5b0-49b2a88ad719, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:471:10232)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:474:180228)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:474:163476

 ❌ Deployment failed: Error: The stack named CdkWorkshopStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: fc313d0f-2bc3-4a4c-8c4d-bf1a0c796c50)" (RequestToken: ed5bbfbd-9f98-84bd-c5b0-49b2a88ad719, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:471:10232)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:474:180228)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:474:163476

The stack named CdkWorkshopStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: fc313d0f-2bc3-4a4c-8c4d-bf1a0c796c50)" (RequestToken: ed5bbfbd-9f98-84bd-c5b0-49b2a88ad719, HandlerErrorCode: InvalidRequest)
`

**Comment by ashishdhingra** [comment]
@silver-mx / @julius-eller Thanks for the report. I will create consolidated PR for updating version of `cdk-dynamo-table-view` for all languages.
