### ISSUE TITLE
Issue with CdkWorkshop typescript

### ISSUE THREAD

**Issue by ravanapel** [aws-samples/aws-cdk-intro-workshop#124]
### What is the problem?

Workshop url: https://cdkworkshop.com/20-typescript/40-hit-counter/200-handler.html

The Typescript CdkWorkshop uses the following import statement:
```js
// file: lambda/hitcounter.js
import { DynamoDB, Lambda } from 'aws-sdk';
```
However, this produces the following error (from the deployed lambda): See Verbose log
I googled the error and found the following stackoverflow page:
[https://stackoverflow.com/questions/56859727/why-do-i-get-a-usercodesyntaxerror-when-i-have-no-syntax-error-in-my-code](https://stackoverflow.com/questions/56859727/why-do-i-get-a-usercodesyntaxerror-when-i-have-no-syntax-error-in-my-code)

The guide uses an ES6 style import, which is not supported by the aws node.js 10.x runtime. I changed it to a standard module require syntax and the function worked as expected.

### Reproduction Steps

cdk deploy with the lambda/hitcounter.js file and look in the cloudwatch logs

### Verbose Log

```
2020-02-16T12:47:27.490Z	undefined	ERROR	Uncaught Exception
{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token {","stack":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token {","    
at _loadUserApp (/var/runtime/UserFunction.js:98:13)","    
at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    
at Object.<anonymous> (/var/runtime/index.js:45:30)","    
at Module._compile (internal/modules/cjs/loader.js:778:30)","    
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    
at Module.load (internal/modules/cjs/loader.js:653:32)","    
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    
at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    
at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    
at startup (internal/bootstrap/node.js:283:19)"]}
```
### Environment

  - **CDK CLI Version:**  1.23.0 (build 01f326e)
  - **Section:**  https://cdkworkshop.com/20-typescript/40-hit-counter/200-handler.html
  - **Browser:**  Firefox
  - **Language:**  TypeScript

**Comment by TheKangaroo** [comment]
For those of use (like me), who never used node before.
"changed it to a standard module require syntax" means changing
```
import { DynamoDB, Lambda } from 'aws-sdk';
```
to
```
const { DynamoDB, Lambda } = require('aws-sdk');
```

This did the tick for me

**Comment by NGL321** [comment]
@TheKangaroo I just talked to one of our JS people and unfortunately it looks like Lambda does not support ES6 syntax at all.

Good catch!

If you would like to put in a PR to fix this, feel free, otherwise I will take care of it soon.

😸

**Comment by TheKangaroo** [comment]
@NGL321 I was just about to start when I noticed @ravanapel already put in a PR  🎉
