### ISSUE TITLE
Cleanup TS

### ISSUE THREAD

**Issue by mhausenblas** [aws-samples/aws-cdk-intro-workshop#126]
## :rocket: Feature Request

In the [TS cleanup step](https://github.com/aws-samples/aws-cdk-intro-workshop/blob/master/workshop/content/20-typescript/60-cleanups/_index.md) one should mention that `cdk destroy` does not clean up everything, for example, the DynamoDB table, the S3 bucket, and the CDKToolkit CFN stack are still left over after the command has completed.

**Comment by NGL321** [comment]
This is a good point. I will make sure an overview of removal policies and the CFN stack get added!

**Comment by peterwoodworth** [comment]
Closing as duplicate of #276
