### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MohamedSherifAbdelsamiea** [aws-samples/aws-cdk-intro-workshop#1278]
### Describe the bug

In page https://cdkworkshop.com/30-python/40-hit-counter/300-resources.html

line handler='hitcount.handler', should be handler='hitcounter.handler',

### Expected Behavior

After CDK Deploy lambda failed due to import wrong handler

### Current Behavior

NA

### Reproduction Steps

NA

**Comment by stefanfreitag** [comment]
Hi @MohamedSherifAbdelsamiea ,

I tried out the Python code available in main branch and it is working for me.

- On page [https://cdkworkshop.com/30-python/40-hit-counter/200-handler.html
](https://cdkworkshop.com/30-python/40-hit-counter/200-handler.html) a file `lambda/hitcount.py` is created. This file contains the actual Lambda function code.
- On page [https://cdkworkshop.com/30-python/40-hit-counter/300-resources.html](https://cdkworkshop.com/30-python/40-hit-counter/300-resources.html) a `HitCounter` class is created. It references  to the previously created Lambda function code:

  ```python
  self._handler = _lambda.Function(
            self, 'HitCountHandler',
            runtime=_lambda.Runtime.PYTHON_3_7,
            handler='hitcount.handler',
            code=_lambda.Code.from_asset('lambda'),
            environment={
                'DOWNSTREAM_FUNCTION_NAME': downstream.function_name,
                'HITS_TABLE_NAME': table.table_name,
            }
        )
  ```
  `_lambda.Code.from_asset('lambda')` gives an inidication on the directory to check and `handler='hitcount.handler'` points to the file and function within the file.

Could you please check if the file names are as expected on our end? If file names are as expected, please provide the error message that you are getting.
