### ISSUE TITLE
.NET version of the workshop producing NuGet package version mismatches

### ISSUE THREAD

**Issue by vgribok** [aws-samples/aws-cdk-intro-workshop#135]
### What is the problem?

.NET version of the workshop has several "`dotnet add package Amazon.CDK.xxxx`" instructions, which may result in project build failures if CDK CLI is not of the latest version. .NET workshop instructions need to be updated to ensure that CLI CDK version is used when adding CDK NuGet packages to the sample project.

### Reproduction Steps

* Install old version of the CDK CLI.
* Follow instructions of the .NET Workshop, specifically where participants are asked to add CDK NuGet packages using "`dotnet add package Amazon.CDK.xxxx`" instructions.
* Check the .csproj file content: observe pre-existing CDK NuGet reference being of the CLI version, while the just-added one(s) being of the latest CDK library version available at NuGet.org.
* Attempt to build, observe failures, usually involving JSII.

### Environment

  - **CDK CLI Version:** 1.31 
  - **Section:** http://localhost:1313/40-dotnet/30-hello-cdk/200-lambda.html#install-the-aws-lambda-construct-library 
  - **Language:** .NET/C#

**Comment by NGL321** [comment]
Hey @vgribok,

After quick review of the workshop, the `Prerequisites` section `/15-prerequisites/500-toolkit` indicates that the user should install the latest version of the CDK Toolkit. This means that when they later add dependencies, they should also be using the latest dependencies.

I understand your concern about potential version breakage, but the only scenario where the CLI will be an older version is if a new CDK version is released (with a breaking change) WHILE the user is completing the workshop. Additionally, if this does happen, the CDK Toolkit will prompt the user that they do not have the latest version installed.

Besides adding additional steps and knowledge requirements to the workshop, getting a specific version of a package the way proposed guides the user to install their dependencies based on an environment variable that could become out of date leading to the same problem as initially discussed.

All that said, I appreciate the report, but I am going to close this issue for now.

😸 😷

**Comment by vgribok** [comment]
I believe that although prerequisites instruct to install latest CDK CLI, real world flow may be more like the situation described in this issues.

1. New CDK project is created where CDK CLI is of latest version X. This will result in NuGet packages added to the project to be also at version X.
2. Two weeks later, after CDK version X+1 is released, CDK NuGet packages referenced by the project are behind. Adding another latest CDK package to the project results in package version mismatch.
3. Given frequent breaking changes in CDK releases, the version mismatch described in this scenario is a real world customer problem that needs addressing. 

Another quick note, PowerShell as of version 6 (now on 7) is fully cross-platform.
