### ISSUE TITLE
300-structure.html contain incorrect path

### ISSUE THREAD

**Issue by devops01ua** [aws-samples/aws-cdk-intro-workshop#1351]
### Describe the bug

https://cdkworkshop.com/20-typescript/20-create-project/300-structure.html
contains:

lib/cdk-workshop-stack.ts
bin/cdk-workshop.ts

 

### Expected Behavior

<img width="285" alt="image" src="https://github.com/aws-samples/aws-cdk-intro-workshop/assets/136992576/deaa0c78-803e-40a4-aa56-a83f747408e1">

### Current Behavior

documentation is outdated

### Reproduction Steps

1) cdk init sample-app --language typescript
2) check bin and lib folders

### Possible Solution

renaming

### CDK CLI Version

2.130.0 (build bd6e5ee)

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@devops01ua Good afternoon. Thanks for opening the issue.

The page https://cdkworkshop.com/20-typescript/20-create-project/100-cdk-init.html has following instructions:
- `Create project directory` with command:
  ```
  mkdir cdk-workshop && cd cdk-workshop
  ```
- cdk init
  ```
  cdk init sample-app --language typescript
  ```

`cdk init` command creates stack and app based on name of the containing directory, which is `cdk-workshop` in this case. The screenshot on the page https://cdkworkshop.com/20-typescript/20-create-project/300-structure.html correctly reflects the directory structure. Just to mention, I used CDK CLI version `2.136.0 (build 94fd33b)`.

<img width="181" alt="structure" src="https://github.com/aws-samples/aws-cdk-intro-workshop/assets/67916761/aa8ce403-7f7d-4d22-a88e-2c314eab1cc1">


Thanks,
Ashish
