### ISSUE TITLE
mvn needs a clean after deleting test directory

### ISSUE THREAD

**Issue by GrahamLea** [aws-samples/aws-cdk-intro-workshop#137]
### What is the problem?
On the "Delete the sample code from your stack" page for Java, the `mvn package` command doesn't work because, while the `src/test/` dir is gone, the compiled test is still in `target/`.

### Reproduction Steps
Follow the workshop up to this point.

### Fix:
* `mvn clean package` gets rid of the compiled test.
* Alternatively, the instruction to delete the `src/test/` tree could be moved to before the first `mvn package` in the workshop.

### Environment
  - **CDK CLI Version:** 1.36.1 (build 4df7dac)
  - **Section:** Delete the sample code from your stack
  - **Language:** Java(TM) SE Runtime Environment (build 9.0.4+11), Apache Maven 3.6.3

**Comment by peterwoodworth** [comment]
Seems this has been addressed. The next step executes `mvn clean package` https://cdkworkshop.com/50-java/30-hello-cdk/100-cleanup.html
