### ISSUE TITLE
In python workshop, there is a problem.

### ISSUE THREAD

**Issue by KIMCAT33** [aws-samples/aws-cdk-intro-workshop#140]
### What is the problem?

In "Writing Constructs" part, there is "Use the hit counter" section. 

I typed "from hitcounter import HitCounter" in my cdkworkshop_stack.py, but when I did sdk deploy command. It couldn't find hitcounter module. So I changed from .hitcounter import Hitcounter and It was fixed. I think you need to check if it's okay or not. 

### Environment

  - **CDK CLI Version:**  1.39.0
  - **Section:**  visual code
  - **Browser:**  Chrome
  - **Language:**  Python

**Comment by gzaal** [comment]
I ran into this issue today in the Python CDK workshop when adding the hitcounter. Currently on line 8 in the cdk_workshop_stack.py file in the tutorial it states: "from .hitcounter import HitCounter" this should be without the . (dot)

like this "from hitcounter import HitCounter"
