### ISSUE TITLE
CDK does not pull same versions for modules but only the latest

### ISSUE THREAD

**Issue by SvenBayerBSHG** [aws-samples/aws-cdk-intro-workshop#141]
### What is the problem?
I did the CDK tutorial and installed in the first step libraries with version 1.45.0. Then, I got an compilation error. The reason was that I added AWS Lambda and it was automatically version 1.47.0 which is incompatible with the other 1.45.0 libraries.

I solved it by up executing:
$ npm install -g npm-check-updates
$ ncu -u
$ npm install 

### Reproduction Steps
Install CDK dependencies with 1.45.0. Then, install AWS Lambda CDK. It will be automaticall version 1.47.0. Then add a Lambda construct. You will get an complication error.

### Environment

  - **CDK CLI Version:** 1.45.0
  - **Section:** Hello Lambda
  - **Browser:** Chrome
  - **Language:** TypeScript

**Comment by NGL321** [comment]
Hi @SvenBayerBSHG,

Thanks for reporting this. We are actually going to adjust the workshop to use a static stable version of the CDK rather than the latest. This update will come in the near future.

In the interim `cdk doctor` should help with that.

**Comment by peterwoodworth** [comment]
Closing since this isn't an issue with the workshop.
