### ISSUE TITLE
missing path of hitcount.handler

### ISSUE THREAD

**Issue by cmrzlg** [aws-samples/aws-cdk-intro-workshop#144]
## :bug: Bug Report
 The sample code of hitcounter.py line 24
           handler='hitcount.handler',
should be:
           handler='lambda/hitcount.handler',

otherwise can't locate hitcount module.

**Comment by NGL321** [comment]
Hey @cmrzlg,

Thank you for the report, and sorry for the delay. Actually, the code is correct as is. The folder is referenced in ln 26 `code=_lambda.Code.asset('lambda'),`. Once the code is located by the cdk you shouldnt need to reference the folder.

Thanks again!
😸 😷
