### ISSUE TITLE
DynamoTableViewer requires update

### ISSUE THREAD

**Issue by NGL321** [aws-samples/aws-cdk-intro-workshop#152]
## :bug: Bug Report

Eladb.DyanmoTableViewer needs some updates:
- Dependency on Amazon.JSII.Runtime < 0.21.0 (for 3.0.6, and < 0.22.0 for 3.1.2).  All the other CDK packages depend on Amazon.JSII.Runtime > 1.9.0. 
- Doesn’t have the update to use Node 12 on Lambda, and still references Node 8, which is no longer supported.
- Specifically calls out old version of package to use as dependency

**Comment by hakanson** [comment]
I also had recent issues running this workshop but was able to get it working with a lower number but more recently built [release](https://github.com/cdklabs/cdk-dynamo-table-viewer/releases)

This syntax for dotnet package [version ranges](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges) kept it below the 3.* release.

```console
dotnet add package Eladb.DynamoTableViewer --version "[0.1.*,3)"
```

I also updated the rest of my `Amazon.CDK` dependencies to be `Version="1.*"` in the `.csproj` file

```console
$ dotnet list package
Project 'CdkWorkshop' has the following package references
   [netcoreapp3.1]: 
   Top-level Package                Requested   Resolved
   > Amazon.CDK                     1.*         1.118.0 
   > Amazon.CDK.AWS.APIGateway      1.*         1.118.0 
   > Amazon.CDK.AWS.DynamoDB        1.*         1.118.0 
   > Amazon.CDK.AWS.Lambda          1.*         1.118.0 
   > Amazon.Jsii.Analyzers          *           1.33.0  
   > Eladb.DynamoTableViewer        [0.1.*,3)   0.1.59  
```

**Comment by ryparker** [comment]
> I also had recent issues running this workshop but was able to get it working with a lower number but more recently built [release](https://github.com/cdklabs/cdk-dynamo-table-viewer/releases)
> 
> This syntax for dotnet package [version ranges](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges) kept it below the 3.* release.
> 
> ```
> dotnet add package Eladb.DynamoTableViewer --version "[0.1.*,3)"
> ```
> 
> I also updated the rest of my `Amazon.CDK` dependencies to be `Version="1.*"` in the `.csproj` file
> 
> ```
> $ dotnet list package
> Project 'CdkWorkshop' has the following package references
>    [netcoreapp3.1]: 
>    Top-level Package                Requested   Resolved
>    > Amazon.CDK                     1.*         1.118.0 
>    > Amazon.CDK.AWS.APIGateway      1.*         1.118.0 
>    > Amazon.CDK.AWS.DynamoDB        1.*         1.118.0 
>    > Amazon.CDK.AWS.Lambda          1.*         1.118.0 
>    > Amazon.Jsii.Analyzers          *           1.33.0  
>    > Eladb.DynamoTableViewer        [0.1.*,3)   0.1.59  
> ```

Applied this add package command to my PR: https://github.com/aws-samples/aws-cdk-intro-workshop/pull/268
