### ISSUE TITLE
Inaccurate info in "/workshop/content/30-python/20-create-project/500-deploy.md"

### ISSUE THREAD

**Issue by angabini** [aws-samples/aws-cdk-intro-workshop#158]
### What is the problem?

in the workshop content page: https://github.com/aws-samples/aws-cdk-intro-workshop/blob/master/workshop/content/30-python/20-create-project/500-deploy.md#lets-deploy

it's stated that:

> This is warning you that deploying the app entails some risk. Since we need to allow the topic to send messages to the queue and we are also creating an IAM User and granting access to the new Buckets

which is not accurate. we are note creating any IAM user/role. only updating the the SNS topic's Access Policy (I believe)

**Comment by peterwoodworth** [comment]
Thank you for submitting this issue. You're right, no IAM user is being created. Only the Python workshop contains this error, but the other languages, while not incorrect, aren't very clear about what's going on. The explanation should be more clear about what's really going on for every description.
