### ISSUE TITLE
`cdk diff` shows no differences

### ISSUE THREAD

**Issue by fdietze** [aws-samples/aws-cdk-intro-workshop#168]
### What is the problem?
In the typescript workshop, under cleanup (https://cdkworkshop.com/20-typescript/30-hello-cdk/100-cleanup.html):

running `cdk diff` shows that there were no differences:
```
cdk diff
Stack CdkWorkshopStack
There were no differences
```

I ran `cdk bootstrap` and `cdk deploy` before, both successful.

Neither adding or removing the suggested code-changes, produces a diff.

### Reproduction Steps
Follow the steps until https://cdkworkshop.com/20-typescript/30-hello-cdk/100-cleanup.html

### Environment

  - **CDK CLI Version:1.69.0 (build 2b474b9)
 
  - **Section: cleanup 
  - **Browser: Chromium 
  - **Language:TypeScript

**Comment by fdietze** [comment]
Ok, it seems like `cdk diff` or `cdk synth` are not triggering the typescript build. Shouldn't these commands trigger it automatically?

I have to run `npm run build` before, then it's working.

**Comment by NGL321** [comment]
Hey @fdietze,

Sorry for the delay in this. I have checked several times, but have been unable to see the behavior you described. My guess is that you did not save the file with the altered stack before running `cdk diff`.

If you think there is more to this, please feel free to leave a comment here and I will investigate again.

**Comment by fdietze** [comment]
I guess it's fine like this.
