### ISSUE TITLE
unable to determine cloud assembly output directory

### ISSUE THREAD

**Issue by ahmad82pkn** [aws-samples/aws-cdk-intro-workshop#172]
### Environment

  - **CDK CLI Version:**  1.70.0 (build c145314)
  - **Section:** aws-cdk-intro-workshop
  - **Browser:** chrome
  - **Language:** TypeScript

I get this error 

```console
 cdk synth
unable to determine cloud assembly output directory. Assets must be defined indirectly within a "Stage" or an "App" scope
```
Any idea, why would this happen? it only happens when i add lambda code below.
```ts
  const hello = new lambda.Function(this, 'HelloHandler', {
      runtime: lambda.Runtime.NODEJS_10_X,    // execution environment
      code: lambda.Code.fromAsset('lambda'),  // code loaded from "lambda" directory
      handler: 'hello.handler'                // file is "hello", function is "handler"
    });
```
If i remove this code and just create SNS/SQS that comes by default in code that works fine.
I have created a file hello.js under directory   "lambda' on same level as LIB/BIN directory are.

Any suggestions , how to fix this error?

I am using Cloud9 if that helps.

Content of hello.js
```js
exports.handler = async function(event) {
  console.log("request:", JSON.stringify(event, undefined, 2));
  return {
    statusCode: 200,
    headers: { "Content-Type": "text/plain" },
    body: `Hello, CDK! You've hit ${event.path}\n`
  };
};
```

Content of actual TS code.
```ts
import * as sns from '@aws-cdk/aws-sns';
import * as subs from '@aws-cdk/aws-sns-subscriptions';
import * as sqs from '@aws-cdk/aws-sqs';
import * as s3 from '@aws-cdk/aws-s3';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';

export class WorkshopTypescriptStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const hello = new lambda.Function(this, 'HelloHandler', {
      runtime: lambda.Runtime.NODEJS_10_X,    // execution environment
      code: lambda.Code.fromAsset('lambda'),  // code loaded from "lambda" directory
      handler: 'hello.handler'                // file is "hello", function is "handler"
    });

    const queue = new sqs.Queue(this, 'WorkshopTypescriptQueue', {
      visibilityTimeout: cdk.Duration.seconds(300)
    });

    const topic = new sns.Topic(this, 'WorkshopTypescriptTopic');
    topic.addSubscription(new subs.SqsSubscription(queue));

  }
}
```

**Comment by rohannap** [comment]
I've encountered the same issue.  I had previously worked my way past this point in the AWS CDK Workshop and got to the testing portion of the workshop.  After two weeks I picked back up on the workshop and am getting this error.  I started over from the beginning and same error.  Very frustrating that I cannot work through a "Hello World" tutorial.

**Comment by peterwoodworth** [comment]
Sorry for the long response time here.

This isn't an issue with the workshop, but due to mismatched package versions. Unfortunate that this isn't clear and lead to frustrations.

https://github.com/aws/aws-cdk/issues/9578#issuecomment-672884639
