### ISSUE TITLE
StandardNpmSynthOptions doesn't contain InstallCommands

### ISSUE THREAD

**Issue by OksanaH** [aws-samples/aws-cdk-intro-workshop#175]
Hello I've pulled the repo, and am getting the error "StandardNpmSynthOptions doesn't contain InstallCommands/BuildCommands" in PipelineStack.cs

![Bug](https://user-images.githubusercontent.com/34384274/97788492-3fe3ff00-1bb1-11eb-8be5-0d32709674b7.PNG)

**Comment by NGL321** [comment]
Hey @OksanaH,

I can confirm this, I will look into a patch ASAP.

😸 😷

**Comment by olivboom** [comment]
@NGL321 It looks to me like the BuildCommands and InstallCommands should be BuildCommand and InstallCommand. The extra "s" isn't required as shown here:
https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.Pipelines.SimpleSynthAction.html#Amazon_CDK_Pipelines_SimpleSynthAction_StandardNpmSynth_Amazon_CDK_Pipelines_IStandardNpmSynthOptions_.

But the type of these commands is string not an array of strings, so not sure how you should be passing multiple commands as is required in InstallCommand. I'm not familiar with .NET but I would say it's a quick patch for someone familiar with the syntax.

**Comment by olivboom** [comment]
However this does leads to other issues down the line of not being able to install dotnet-sdk-3.1 on Code Build which i think is related to this thread - https://github.com/dotnet/core/issues/4360

**Comment by OksanaH** [comment]
I think this command will do the .NET Core installation: "npm install -g aws-cdk && wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && apt-get update && apt-get install -y apt-transport-https && apt-get update && apt-get install -y dotnet-sdk-3.1"

**Comment by TimTraylor** [comment]
@OksanaH Thank you! That got me over one hurdle.

**Comment by hakanson** [comment]
Running this just 2 weeks ago, I used these lines of code.  No need to install dotnet-sdk-3.1 on CodeBuild and I targeted the `src` directory with my `dotnet build` command.

```csharp
InstallCommand = "npm install -g aws-cdk", 
BuildCommand = "dotnet build src", // Language-specific build cmd
```
