### ISSUE TITLE
The Python section of the CDK Workshop needs updating to match 1.71

### ISSUE THREAD

**Issue by SomayaB** [aws-samples/aws-cdk-intro-workshop#179]
## :rocket: Feature Request

> Originally posted by @WillBroadbentMSM in https://github.com/aws/aws-cdk/issues/11304

### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Environment

  - **CDK CLI Version:** 
  - **Section:** 
  - **Browser:** 
  - **Language:**

**Comment by peterwoodworth** [comment]
This is really unspecific. If anyone knows exactly what this refers to, let me know
