### ISSUE TITLE
Typo in Polish Pipeline content

### ISSUE THREAD

**Issue by burgwyn** [aws-samples/aws-cdk-intro-workshop#181]
### What is the problem?
Typo in the last paragraph of the Polish Pipelines section in the Typescript Workshop - "Conratulations"

![image](https://user-images.githubusercontent.com/661204/99610274-802fe380-29df-11eb-86d7-e996a77e49ec.png)

### Reproduction Steps

Browse site > Typescript Workshop > Advanced Topics > [Polish Pipeline](https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.html)

### Verbose Log

N/A

### Environment

N/A

### Other information 

N/A

**Comment by SomayaB** [comment]
Hi @burgwyn, thanks for the catch and for putting in a PR, much appreciated! 👍
