### ISSUE TITLE
Directions on "Create Stage" Page results in a CodeBuild error "no such file in directory"

### ISSUE THREAD

**Issue by jspooner** [aws-samples/aws-cdk-intro-workshop#184]
### What is the problem?

I'm on the [Create Stage](https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.html) tutorial and I'm unable to successfully run my pipeline due to an error in the Build stage.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/24090/103100933-df2ddd00-45c9-11eb-8928-a1654772e60f.png">

I see the build dir set to `CODEBUILD_SRC_DIR=/codebuild/output/src213311547/src` then  it attempts to access `/codebuild/output/src213311547/src/lambda` and that directory is not there.  I can't seem to find what code is looking at that directory.

```
[Container] 2020/12/24 16:34:58 Running command npx cdk synth
npx: installed 193 in 5.783s
ENOENT: no such file or directory, stat '/codebuild/output/src213311547/src/lambda'
Subprocess exited with error 1
[Container] 2020/12/24 16:35:09 Command did not exit successfully npx cdk synth exit status 1
[Container] 2020/12/24 16:35:09 Phase complete: BUILD State: FAILED
[Container] 2020/12/24 16:35:09 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npx cdk synth. Reason: exit status 1
```

pipeline-stack.ts

```typescript
import * as cdk from '@aws-cdk/core';
import * as codecommit from '@aws-cdk/aws-codecommit';
import * as codepipeline from '@aws-cdk/aws-codepipeline';
import * as codepipeline_actions from '@aws-cdk/aws-codepipeline-actions';
import { SimpleSynthAction, CdkPipeline } from '@aws-cdk/pipelines';
import { WorkshopPipelineStage } from './pipeline-stage';

export class WorkshopPipelineStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps)  {
    super(scope, id, props);

    const repo = new codecommit.Repository(this, 'WorkshopRepo', {
      repositoryName: 'WorkshopRepo'
    });

    // Defines the artifact representing the source code
    const sourceArtifact = new codepipeline.Artifact();
    // Defines the artifact representing the cloud assembly
    // cloudformation template + all other assets
    const cloudAssemblyArtifact = new codepipeline.Artifact();

    // The basic pipeline declaration
    const pipeline = new CdkPipeline(this, 'Pipeline', {
      pipelineName: 'WorkshopPipeline',
      cloudAssemblyArtifact,
      // Generates the source artifact from the repo we created in the last step
      sourceAction: new codepipeline_actions.CodeCommitSourceAction({
        actionName: 'CodeCommit',
        output: sourceArtifact,
        repository: repo
      }),
      // Builds our source code outlined above into a could assembly artifact
      synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        buildCommand: 'npm run build'
      })
    });

    const deploy = new WorkshopPipelineStage(this, 'Deploy');
    pipeline.addApplicationStage(deploy);
  }
}
```

### Verbose Log

<img width="840" alt="image" src="https://user-images.githubusercontent.com/24090/103100869-8bbb8f00-45c9-11eb-9061-7900f85e58b6.png">

### Environment

  - **CDK CLI Version:** 1.78 and 1.80.0 (build 31132ca)
  - **Section:** https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.html
  - **Browser:** n/a
  - **Language:** TypeScript

**Comment by jonathanlemonsonos** [comment]
hey! it looks like you may be ignoring your lambda js files.

try adding this to your gitignore and making sure the js files make it to your repo:
`!lambda/*.js`

**Comment by jspooner** [comment]
@jonathanlemonsonos very kind of you!  This was the issue.

I believe the [CDK Pipeline](https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines.html) section needs to note this.  I'm going to investigate this a little more and possibly make a PR for a doc fix.
