### ISSUE TITLE
Java Workshop: Lambda deployment fails

### ISSUE THREAD

**Issue by dvldi** [aws-samples/aws-cdk-intro-workshop#186]
### What is the problem?
When trying to deploy the sample Lambda as described in the _Hello Lambda_-section in the Java Workshop, CDK failed with:

> Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ********-****-****-****-************; Proxy: null)

(Request ID anonymized)

It turns out, the problem is due to a problem in Node.js 15.6 (see https://github.com/aws/aws-cdk/issues/12536) and the only solution is using an earlier version (<15, 15.5 is said to have the same problem).

The problem should be mentioned in the workshop, so people don't need to spend lots of time on finding the solution.

### Reproduction Steps

Just follow the steps in the workshop, using Node.js 15.6.

### Environment

  - **CDK CLI Version:** 1.78.0 (build 2c74f4c)
  - **Section:** Java Workshop > Hello CDK! > Hello Lambda
  - **Language:** Java

**Comment by peterwoodworth** [comment]
Thanks for submitting this issue! 

This was due to a breaking change introduced to the CDK which has since been resolved. See this issue for more information: aws/aws-cdk/issues/12536.
