### ISSUE TITLE
Uploaded file must be a non-empty zip | Typescript CDK Intro

### ISSUE THREAD

**Issue by goldendemise** [aws-samples/aws-cdk-intro-workshop#187]
### The Question

I'm following the CDK intro (typescript) and am running into an inability to 'CDK deploy' when introducing 'lambda/hello.js' in the 'add a lambda function to your stack' section.

Specifically, I get:
Uploaded file must be a non-empty zip (Service: AWSLambdaInternal)2:12:52 AM | CREATE_FAILED        | AWS::Lambda::Function | HelloHandler

I typed it out manually initially, went back and copy/pasted to rule out user error, and still get an error during deploy.
Do you have any guidance for troubleshooting this error?
I'm not experienced in TypeScript, so I feel I may be bungling something obvious here.

I re-read the tutorial and saw nothing about needing to zip/unzip, and the environment in question has already been bootstrapped, which seems to be implied as all that's needed in the tutorial

I've placed my code here to verify I didn't make obvious mistakes: https://github.com/drudgesentinel/cdk-example
### Environment

  - **CDK CLI Version:** 
  - 1.87.1 (build 9eeaa93)
  - **Section:** 
  - https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html
  - **Browser:** 
  - Firefox
  - **Language:** 
  - Typescript

**Comment by akefirad** [comment]
See aws/aws-cdk/issues/12536.

**Comment by peterwoodworth** [comment]
This was due to a breaking change introduced to the cdk. The issue has since been resolved
