### ISSUE TITLE
Java Workshop: Construct example not working

### ISSUE THREAD

**Issue by dvldi** [aws-samples/aws-cdk-intro-workshop#189]
### What is the problem?
If done according to the example in the Java Workshop, packaging the project results in:
`Failed to execute goal on project cdk-workshop: Could not resolve dependencies for project com.myorg:cdk-workshop:jar:0.1: Failed to collect dependencies for com.myorg:cdk-workshop:jar:0.1: Could not resolve version conflict among [software.amazon.awscdk:core:jar:1.78.0 -> software.amazon.awscdk:cdk-cloud-assembly-schema:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:core:jar:1.78.0 -> software.amazon.awscdk:cdk-cx-api:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:core:jar:1.78.0 -> software.amazon.awscdk:cdk-region-info:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:core:jar:1.78.0 -> software.constructs:constructs:jar:[3.2.0,4.0.0) -> software.amazon.jsii:jsii-runtime:jar:[1.17.1,2.0.0), software.amazon.awscdk:core:jar:1.78.0 -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:cdk-assets:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:certificatemanager:jar:[1.78.0,1.78.0] -> software.amazon.awscdk:route53:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:certificatemanager:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:cloudwatch:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:ec2:jar:[1.78.0,1.78.0] -> software.amazon.awscdk:ssm:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:ec2:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:elasticloadbalancingv2:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:iam:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:logs:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:s3:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.awscdk:s3-assets:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.78.0 -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.78.0 -> software.amazon.awscdk:applicationautoscaling:jar:[1.78.0,1.78.0] -> software.amazon.awscdk:autoscaling-common:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.78.0 -> software.amazon.awscdk:applicationautoscaling:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.78.0 -> software.amazon.awscdk:kms:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.78.0 -> software.amazon.awscdk:cdk-customresources:jar:[1.78.0,1.78.0] -> software.amazon.awscdk:cloudformation:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.78.0 -> software.amazon.awscdk:cdk-customresources:jar:[1.78.0,1.78.0] -> software.amazon.awscdk:sns:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.78.0 -> software.amazon.awscdk:cdk-customresources:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.78.0 -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:lambda:jar:1.78.0 -> software.amazon.awscdk:codeguruprofiler:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:lambda:jar:1.78.0 -> software.amazon.awscdk:ecr:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:lambda:jar:1.78.0 -> software.amazon.awscdk:ecr-assets:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:lambda:jar:1.78.0 -> software.amazon.awscdk:efs:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:lambda:jar:1.78.0 -> software.amazon.awscdk:events:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:lambda:jar:1.78.0 -> software.amazon.awscdk:sqs:jar:[1.78.0,1.78.0] -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), software.amazon.awscdk:lambda:jar:1.78.0 -> software.amazon.jsii:jsii-runtime:jar:[1.15.0,2.0.0), com.github.eladb:cdk-dynamo-table-viewer:jar:[3.0.6,4] -> software.amazon.jsii:jsii-runtime:jar:[0.21.1,0.22.0)] -> [Help 1]`

Using version *3.0.6.* for `cdk-dynamo-table-viewer` enables successful packaging, but when trying to deploy (`cdk deploy`), it fails with:
`-:--:-- PM | CREATE_FAILED        | AWS::Lambda::Function       | ViewerHitCount/Rendered
The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Servic
e: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ********-****-****-****-************; Proxy: null)
`

Using version *3.1.2* or *LATEST* leads to the packaging problem mentioned initially again.

### Reproduction Steps
Just follow the steps in the respective section in the workshop.

### Environment

  - **CDK CLI Version:** 1.78.0 (build 2c74f4c)
  - **Section:** Java Workshop > Using construct libraries
  - **Language:** Java

**Comment by gelpenaddict** [comment]
Similarly with a newer version:
> mvn compile -e   
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< com.myorg:cdk-workshop >-----------------------
[INFO] Building cdk-workshop 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for software.constructs:constructs:jar:3.2.110 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.685 s
[INFO] Finished at: 2021-03-07T12:19:00-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cdk-workshop: Could not resolve dependencies for project com.myorg:cdk-workshop:jar:0.1: Failed to collect dependencies for com.myorg:cdk-workshop:jar:0.1: Could not resolve version conflict among [software.amazon.awscdk:core:jar:1.91.0 -> software.amazon.awscdk:cdk-cloud-assembly-schema:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:core:jar:1.91.0 -> software.amazon.awscdk:cdk-cx-api:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:core:jar:1.91.0 -> software.amazon.awscdk:cdk-region-info:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:core:jar:1.91.0 -> software.constructs:constructs:jar:[3.2.0,4.0.0) -> software.amazon.jsii:jsii-runtime:jar:[1.24.0,2.0.0), software.amazon.awscdk:core:jar:1.91.0 -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:certificatemanager:jar:[1.91.0,1.91.0] -> software.amazon.awscdk:route53:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:certificatemanager:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:cloudwatch:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:cognito:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:ec2:jar:[1.91.0,1.91.0] -> software.amazon.awscdk:ssm:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:ec2:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:elasticloadbalancingv2:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:iam:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:logs:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:s3:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:s3-assets:jar:[1.91.0,1.91.0] -> software.amazon.awscdk:cdk-assets:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.awscdk:s3-assets:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:apigateway:jar:1.91.0 -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.91.0 -> software.amazon.awscdk:applicationautoscaling:jar:[1.91.0,1.91.0] -> software.amazon.awscdk:autoscaling-common:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.91.0 -> software.amazon.awscdk:applicationautoscaling:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.91.0 -> software.amazon.awscdk:kms:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.91.0 -> software.amazon.awscdk:cdk-customresources:jar:[1.91.0,1.91.0] -> software.amazon.awscdk:cloudformation:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.91.0 -> software.amazon.awscdk:cdk-customresources:jar:[1.91.0,1.91.0] -> software.amazon.awscdk:sns:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.91.0 -> software.amazon.awscdk:cdk-customresources:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:dynamodb:jar:1.91.0 -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:lambda:jar:1.91.0 -> software.amazon.awscdk:codeguruprofiler:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:lambda:jar:1.91.0 -> software.amazon.awscdk:ecr:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:lambda:jar:1.91.0 -> software.amazon.awscdk:ecr-assets:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:lambda:jar:1.91.0 -> software.amazon.awscdk:efs:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:lambda:jar:1.91.0 -> software.amazon.awscdk:events:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:lambda:jar:1.91.0 -> software.amazon.awscdk:sqs:jar:[1.91.0,1.91.0] -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), software.amazon.awscdk:lambda:jar:1.91.0 -> software.amazon.jsii:jsii-runtime:jar:[1.21.0,2.0.0), com.github.eladb:cdk-dynamo-table-viewer:jar:[3.0.6,4) -> software.amazon.jsii:jsii-runtime:jar:[0.21.1,0.22.0)] -> [Help 1]

**Comment by gelpenaddict** [comment]
Any ETA on this?

**Comment by sreev** [comment]
This worked for me at today's aws cdk workshop.

`
        <dependency>
            <groupId>com.github.eladb</groupId>
            <artifactId>cdk-dynamo-table-viewer</artifactId>
            <version>3.0.7</version>
        </dependency>

`

3.0.5 didn't work ; mvn package fails
3.0.6 didn't work; mvn package successful; but cdk deploy fails; looking for wrong nodejs version.
3.1.2 didn't work; mvn package fails

**Comment by ryparker** [comment]
I was able to reproduce this using the code in `code/java/main-workshop` running `npx cdk synth`

I believe the issues is caused by incompatible jsii-runtime dependencies. The cdk-dynamo-table-viewer requires a specific (older) version of jsii-runtime that is incompatible with the version that the awscdk packages require.

Sreev's workaround worked for me:

> This worked for me at today's aws cdk workshop.
> 
> ```
>         <dependency>
>             <groupId>com.github.eladb</groupId>
>             <artifactId>cdk-dynamo-table-viewer</artifactId>
>             <version>3.0.7</version>
>         </dependency>
> ```
> 
> 3.0.5 didn't work ; mvn package fails
> 3.0.6 didn't work; mvn package successful; but cdk deploy fails; looking for wrong nodejs version.
> 3.1.2 didn't work; mvn package fails

I will create a PR with this fix applied.
