### ISSUE TITLE
Typescript table.grantReadWriteData cannot grant lambda handler permission

### ISSUE THREAD

**Issue by shauwang** [aws-samples/aws-cdk-intro-workshop#193]
### What is the problem?

On page https://cdkworkshop.com/20-typescript/40-hit-counter/600-permissions.html
I tried to grant lambda access to read/write to dynamoDB, but i get an error message shown below: 

### Verbose Log

TS2345: Argument of type 'Function' is not assignable to parameter of type 'IGrantable'.
  The types of 'grantPrincipal.addToPolicy' are incompatible between these types.
    Type '(statement: import("/home/ec2-user/environment/cdk-workshop/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement) => boolean' is not assignable to type '(statement: import("/home/ec2-user/environment/cdk-workshop/node_modules/@aws-cdk/aws-dynamodb/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement) => boolean'.
      Types of parameters 'statement' and 'statement' are incompatible.
        Type 'import("/home/ec2-user/environment/cdk-workshop/node_modules/@aws-cdk/aws-dynamodb/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement' is not assignable to type 'import("/home/ec2-user/environment/cdk-workshop/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement'.
          Types have separate declarations of a private property 'action'.

33       table.grantReadWriteData(this.handler);

### Environment

  - **CDK CLI Version:**  1.89
  - **Section:**  https://cdkworkshop.com/20-typescript/40-hit-counter/600-permissions.html 
  - **Browser:**  Chrome
  - **Language:**  Typescript

**Comment by stringbeans** [comment]
also experiencing this issue with CDK CLI 1.94.1

**Comment by johndierks** [comment]
I had the same issue and fount [this issue](https://github.com/aws/aws-cdk/issues/6744) which was causing the issue. I had mismatched sub-dependancies in my `package.json`.

Once that was cleaned up and I ran `npm install` again I got further in the demo.

**Comment by peterwoodworth** [comment]
This is due to mismatched versions in package.json, you got it right!
