### ISSUE TITLE
Tpescript CDK workshop: Found unmatched type but should match

### ISSUE THREAD

**Issue by xyz8983** [aws-samples/aws-cdk-intro-workshop#201]
### What is the problem?
When following the CDK workshop example in the step of adding [Stage](https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.html) to pipeline:

`const deployStage = pipeline.addApplicationStage(deploy);` 
 I got an error message saying:

<my_project_root>/node_modules/@aws-cdk/cx-api/lib/cloud-assembly").CloudAssemblyBuilder' is not assignable to type <my_project_root>/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/cx-api/lib/cloud-assembly").CloudAssemblyBuilder'

### Reproduction Steps
The problem should be able to be reproduced by following the "add Stage to pipeline" step in the Typescript CDKworkshop section ADD APPLICATION TO PIPELINE, link [here](https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/4000-build-stage.html)

### Environment

  - **CDK CLI Version:**  1.91.0 (build 0f728ce)
  - **Section:** ADD APPLICATION TO PIPELINE, add stage to pipeline step
  - **Browser:**  chrome
  - **Language:**  Typescript

**Comment by faithege** [comment]
I've also encountered this type error, thanks for reporting

**Comment by peterwoodworth** [comment]
I can't seem to reproduce this, can someone please ping me if they run into this error again? Thanks

**Comment by oliwerhelsen** [comment]
I also got this error. @peterwoodworth  Which version of the cdkpiplines are you running?

**Comment by ilenhart** [comment]
The workshop package.json may have inconsistent versions by the time you get to the pipelines section.  I encountered this same problem, and manually updated all @aws-cdk/* references in package.json to latest versions (1.120.0) and this resolved the error.
