### ISSUE TITLE
Typescript - Create a Test for the Lambda Function

### ISSUE THREAD

**Issue by nmeddin** [aws-samples/aws-cdk-intro-workshop#216]
Expected to fail like this:

>   ● Lambda Has Environment Variables
  ...
  ...
  "Environment": {
              "Variables": {
                "DOWNSTREAM_FUNCTION_NAME": {
                  "Ref": "TestFunctionXXXXX"
                },
                "HITS_TABLE_NAME": {
                  "Ref": "MyTestConstructHitsXXXXX"
                }
              }
            }

Instead fails like this:

> ● Lambda Has Environment Variables

    None of 2 resources matches resource 'AWS::Lambda::Function' with {
      "$objectLike": {
        "Environment": {
          "Variables": {
            "DOWNSTREAM_FUNCTION_NAME": "TestFunction",
            "HITS_TABLE_NAME": "MyTestConstructHits"
          }
        }
      }
    }.
    - Field Environment missing in:
        {
          "Type": "AWS::Lambda::Function",
          "Properties": {
            "Code": {
              "ZipFile": "test"
            },
            "Role": {
              "Fn::GetAtt": [
                "TestFunctionServiceRole6ABD93C7",
                "Arn"
              ]
            },
            "Handler": "lambda.handler",
            "Runtime": "nodejs10.x"
          },
          "DependsOn": [
            "TestFunctionServiceRole6ABD93C7"
          ]
        }
    - Field Environment mismatch: Field Variables mismatch: Field DOWNSTREAM_FUNCTION_NAME mismatch: Object type mismatch, Field HITS_TABLE_NAME mismatch: Object type mismatch in:
        {
          "Type": "AWS::Lambda::Function",
          "Properties": {
            "Code": {
              "S3Bucket": {
                "Ref": "AssetParameters7a8aa4b926e0a549433bf12096ece0cf5a19e630285c664cc6a90fc481403aa2S3Bucket81C36471"
              },
              "S3Key": {
                "Fn::Join": [
                  "",
                  [
                    {
                      "Fn::Select": [
                        0,
                        {
                          "Fn::Split": [
                            "||",
                            {
                              "Ref": "AssetParameters7a8aa4b926e0a549433bf12096ece0cf5a19e630285c664cc6a90fc481403aa2S3VersionKey831E877B"
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "Fn::Select": [
                        1,
                        {
                          "Fn::Split": [
                            "||",
                            {
                              "Ref": "AssetParameters7a8aa4b926e0a549433bf12096ece0cf5a19e630285c664cc6a90fc481403aa2S3VersionKey831E877B"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                ]
              }
            },
            "Role": {
              "Fn::GetAtt": [
                "MyTestConstructHitCounterHandlerServiceRoleD0F1215D",
                "Arn"
              ]
            },
            "Environment": {
              "Variables": {
                "DOWNSTREAM_FUNCTION_NAME": {
                  "Ref": "TestFunction22AD90FC"
                },
                "HITS_TABLE_NAME": {
                  "Ref": "MyTestConstructHits24A357F0"
                }
              }
            },
            "Handler": "hitcounter.handler",
            "Runtime": "nodejs10.x"
          },
          "DependsOn": [
            "MyTestConstructHitCounterHandlerServiceRoleDefaultPolicy8F2C3785",
            "MyTestConstructHitCounterHandlerServiceRoleD0F1215D"
          ]
        }

      30 |     });
      31 |     // THEN
    > 32 |     expectCDK(stack).to(haveResource("AWS::Lambda::Function", {
         |                      ^
      33 |       Environment: {
      34 |         Variables: {
      35 |           DOWNSTREAM_FUNCTION_NAME: "TestFunction",

      at HaveResourceAssertion.assertOrThrow (node_modules/@aws-cdk/assert/lib/assertions/have-resource.ts:100:13)
      at StackInspector._to (node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (test/hitcounter.test.ts:32:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        3.185 s
Ran all test suites.

My test code:

test('Lambda Has Environment Variables', () => {
    const stack = new cdk.Stack();
    // WHEN
    new HitCounter(stack, 'MyTestConstruct', {
        downstream: new lambda.Function(stack, 'TestFunction', {
            runtime: lambda.Runtime.NODEJS_10_X,
            handler: 'lambda.handler',
            code: lambda.Code.fromInline('test')
        })
    });
    // THEN
    expectCDK(stack).to(haveResource("AWS::Lambda::Function", {
        Environment: {
            Variables: {
                DOWNSTREAM_FUNCTION_NAME: "TestFunction",
                HITS_TABLE_NAME: "MyTestConstructHits"
            }
        }
    }));
})

https://cdkworkshop.com/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.html#create-a-test-for-the-lambda-function

**Comment by peterwoodworth** [comment]
Sorry @nmeddin, could you clarify exactly what this issue is about? Thanks
