### ISSUE TITLE
Python Workshop documentation errors

### ISSUE THREAD

**Issue by pcolmer** [aws-samples/aws-cdk-intro-workshop#222]
### What is the problem?
There seem to be errors in the Python Workshop. For example, https://cdkworkshop.com/30-python/20-create-project/300-structure.html says "As you can see, our app was created with two instances of our sample CDK stack (CdkWorkshopStack)." but the app does not appear to be using two instances.

In addition, https://cdkworkshop.com/30-python/20-create-project/400-synth.html says "Because our app includes two stacks we need to tell the cdk synth command which stack we want to synthesize." but then proceeds to call `cdk synth` without specifying which stack.

Did this project perhaps have two stacks in the past and it has been changed to use one stack and the workshop docs are now out of sync?

**Comment by ThePrankMonkey** [comment]
On page https://cdkworkshop.com/30-python/20-create-project/500-deploy.html, there's an error under "Let's Deploy".

> ## Let’s deploy
> Use `cdk deploy` to deploy a CDK app:
> `cdk deploy cdkworkshop`

The last line needs to be `cdk deploy`. At least when using cdk version 1.116.0 (build d04661d). If I try to run `cdk deploy cdkworkshop`, I get no output at all.
