### ISSUE TITLE
cdkworkshop: some final page links don't go to the right places

### ISSUE THREAD

**Issue by pcolmer** [aws-samples/aws-cdk-intro-workshop#223]
### What is the problem?
https://cdkworkshop.com/70-conclusion.html has some links to take you to other places for information. Some of these don't go to the correct place, leaving the learner to potentially struggle to find what they were looking for.

Particularly "Dive deeper into CDK Concepts: Constructs, Apps and Stacks, Logical IDs, Environments, Contexts, and Assets" where, for example, "Apps and Stacks" wants to go to https://docs.aws.amazon.com/CDK/latest/userguide/apps_and_stacks.html but content has been split into separate pages: https://docs.aws.amazon.com/cdk/latest/guide/apps.html and https://docs.aws.amazon.com/cdk/latest/guide/stacks.html

"CDK Concepts" wants to go to https://docs.aws.amazon.com/CDK/latest/userguide/concepts.html but the correct URL seems to be https://docs.aws.amazon.com/cdk/latest/guide/core_concepts.html

There may be others ...

**Comment by peterwoodworth** [comment]
Thank you for catching these issues! would you be willing to submit a PR which fixes these links?
