### ISSUE TITLE
Typescript - Update Node version

### ISSUE THREAD

**Issue by javydekoning** [aws-samples/aws-cdk-intro-workshop#231]
### What is the problem?

Workshop uses EOL version of Node Lambda @ https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html

EOL July 30, 2021: https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

### Reproduction Steps

N/A

### Verbose Log

N/A

### Environment

  - **CDK CLI Version:** 1.112
  - **Language:** TypeScript

**Comment by peterwoodworth** [comment]
Thanks for submitting this report, is this something you'd be willing to create a PR for?

**Comment by javydekoning** [comment]
Yes, I have reserved some time for this tomorrow.
