### ISSUE TITLE
Testing Construct Broken Link

### ISSUE THREAD

**Issue by shdobxr** [aws-samples/aws-cdk-intro-workshop#233]
### What is the problem?
Within the workshop [here](https://cdkworkshop.com/20-typescript/70-advanced-topics/100-construct-testing.html) there is a link to "read the docs" the link is stale.

please read the docs [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/assert/README.md)

### Reproduction Steps
Click link in description... no worky.

### Verbose Log
We don't need to see these droids

### Environment
  - **Section:** TESTING CONSTRUCTS
  - **Browser:** All
  - **Language:** TypeScript

### Other information 
Not needed

**Comment by peterwoodworth** [comment]
This should be the proper link: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/assert-internal/README.md

Would you be willing to submit a pr for this @shdobxr? Ping me to let me know
