### ISSUE TITLE
New to cdk, trying to use the tutorial with a JAVA handler and fail

### ISSUE THREAD

**Issue by ydl1991** [aws-samples/aws-cdk-intro-workshop#234]
### The Question

I was following the tutorial and at first write js handler and everything works fine. Later I want to try write a Java handler and test it. I added the java file in the same lambda directory with package name example, class name MyHandler, writing a simple java handler returning the same info as the js handler. I then go back to stack and change the props, change Runtime to JAVA_8, change handler to example.MyHandler (also tried example.MyHandler::handleRequest), and then deploy it.

But when I try to test it on lambda console, it gives ClassNotFound error, it can't find my example.MyHandler class. Anyone know what's wrong? or is it possible to add a handler version in Java to the tutorial?

### Environment

  - **CDK CLI Version:** 
  - **Section:** 
  - **Browser:** 
  - **Language:**

**Comment by peterwoodworth** [comment]
Hmmm I'm running into this issue as well @ydl1991, I've never created a lambda function in java before though so I'm not sure if I'm doing something wrong. I'll see if I can figure this out

**Comment by peterwoodworth** [comment]
This is due to Java being a compiled language. You can't deploy the code as simply as you can with js or python; you need to deploy a compiled program and its dependencies in a container or zip file.

Here's an example which does this with the CDK: [Link to Stack](https://github.com/aws-samples/cdk-lambda-packaging-java/blob/main/infrastructure/src/main/java/com/myorg/InfrastructureStack.java), [Link to Function](https://github.com/aws-samples/cdk-lambda-packaging-java/blob/main/software/FunctionOne/src/main/java/helloworld/App.java)

I hope this helps. We have it on our agenda to have each workshop deploy the lambda function in the same language as the workshop 😄

**Comment by ydl1991** [comment]
Thank you so much for explaining it! And yes, having each workshop deploy lambda in the same language is definitely a big help for newbies like me!

**Comment by peterwoodworth** [comment]
No problem @ydl1991, do you still need any help with this?

**Comment by ydl1991** [comment]
I just started looking into it, regarding how to deploy the function code as compiled program in container or zip, is it the step showing in this page? https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html

**Comment by ydl1991** [comment]
still not quite get on how to mannually upload the deployed package correctly. I follow this post: https://docs.aws.amazon.com/lambda/latest/dg/java-package.html, and build the deploy package using Maven, which generates a jar file. then I go to lambda console and mannually upload the jar file to the source code section. And the test still fail.

Is there any documents you are aware of that shows the process of deploying a compiled program and in container or zip? @peterwoodworth

**Comment by peterwoodworth** [comment]
Gonna be honest with you @ydl1991, I've never actually deployed a lambda function in Java before. So unfortunately I won't be of much help here. Here's a tutorial which looks helpful: https://www.baeldung.com/java-aws-lambda

**Comment by ydl1991** [comment]
@peterwoodworth  thanks , I was just thinking that if my handler code need to be in a seperate package from my cdk app stack package? cuz we need to compile just the java handler code itself and deploy the jar file, right?

**Comment by peterwoodworth** [comment]
Were you able to figure this out @ydl1991? Sorry for leaving you hanging here

**Comment by NGL321** [comment]
Hey @ydl1991,

Did you figure out the asset deployment for Java-based lambdas? If you haven't, consider checking out the Java examples in the [cdk examples repo](https://github.com/aws-samples/aws-cdk-examples)
