### ISSUE TITLE
Inline source not allowed for nodejs14.x

### ISSUE THREAD

**Issue by jizusun** [aws-samples/aws-cdk-intro-workshop#242]
### What is the problem?

Tests failed because of `nodejs14.x`

### Reproduction Steps

```
cd code/typescript/tests-workshop
npm i
npx jest
```

### Verbose Log

```
 FAIL  test/hitcounter.test.js
  ● DynamoDB Table Created

    Inline source not allowed for nodejs14.x

       7 |     const stack = new cdk.Stack();
       8 |
    >  9 |     const tableCreateLambda = new lambda.Function(stack, 'TestFunction', {
         |                               ^
      10 |         runtime: lambda.Runtime.NODEJS_14_X,
      11 |         handler: 'lambda.handler',
      12 |         code: lambda.Code.inline('test')

      at verifyCodeConfig (node_modules/@aws-cdk/aws-lambda/lib/function.ts:1022:11)
      at new Function (node_modules/@aws-cdk/aws-lambda/lib/function.ts:584:5)
      at Object.<anonymous> (test/hitcounter.test.ts:9:31)

```

### Environment

  - **CDK CLI Version:**   `❯ cdk version 1.115.0 (build f0ca40f)`
  - **Section:** : <https://cdkworkshop.com/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.html>
  - **Browser:**  n/a
  - **Language:**  Typescript

**Comment by NGL321** [comment]
Hey @jizusun,

Thank you for reporting this! It seems there is a little confusion in that section between `from_asset` and `fromInline`. If you use `from_asset` you should not have any trouble.

We will fix this as soon as possible!

😸 😷

**Comment by Chandrian** [comment]
Hello @NGL321 , the bug is related to the fromInline method not working with NODEJS_14_X as it's working perfectly fine if you use NODEJS_12_X. Using the from_asset method would force the tester to have a dummy lambda function to be used for such a test, which would be a pain.
