### ISSUE TITLE
Incorrect casing of class name in a code snippet markdown file

### ISSUE THREAD

**Issue by aabragan** [aws-samples/aws-cdk-intro-workshop#244]
### What is the problem?
In the Python workshop, in the `CLEANUP SAMPLE` page (https://cdkworkshop.com/30-python/30-hello-cdk/100-cleanup.html) the class name in the code snippet is incorrectly cased causing the code to break if you copy and paste the code snippet.

### Reproduction Steps
https://cdkworkshop.com/30-python/30-hello-cdk/100-cleanup.html
if you copy and paste the first code snippet into your code editor and try to run, you will get an error when you run `cdk diff` right after

### Verbose Log
```
Traceback (most recent call last):
  File "/Users/aabragan/Documents/dev-projects/cdk-workshop-py/app.py", line 5, in <module>
    from cdk_workshop_py.cdk_workshop_py_stack import CdkWorkshopPyStack
ImportError: cannot import name 'CdkWorkshopPyStack' from 'cdk_workshop_py.cdk_workshop_py_stack' (/Users/aabragan/Documents/dev-projects/cdk-workshop-py/cdk_workshop_py/cdk_workshop_py_stack.py)
```
### Environment

  - **CDK CLI Version:** 1.115.0
  - **Section:** Python Workshop -> Cleanup Sample
  - **Browser:** all
  - **Language:** Python

**Comment by ryparker** [comment]
Hey @aabragan :wave:

Thanks for reporting this.

I'll mark this as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

**Comment by aabragan** [comment]
Hi @ryparker 

I went through the entire tutorial and made sure the name was consistent throughout. I just pushed my changes. My PR should be ready for review.
