### ISSUE TITLE
Python pipeline workshop typo and error

### ISSUE THREAD

**Issue by HybridNeos** [aws-samples/aws-cdk-intro-workshop#263]
### What is the problem?
The page https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/1000-setting-up.html has an issues. They are namely that app.py has a typo where *from cdk-workshop.pipeline_stack import WorkshopPipelineStack* should be remove the dash and pipeline_stack.py should not have the *from pipeline_stage import WorkshopPipelineStage* line yet.

### Reproduction Steps
Issues arise when trying to boostrap via the provided command *npx cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess*

### Verbose Log
  Could not find a version that satisfies the requirement pypiworkshop_stack (from versions: )
No matching distribution found for pypiworkshop_stack

### Environment

  - **CDK CLI Version:** 1.118.0 
  - **Section:** Getting started with pipelines
  - **Language:** Python

**Comment by ryparker** [comment]
Thanks for opening this issue. I've got a fix implemented here: https://github.com/aws-samples/aws-cdk-intro-workshop/pull/266
