### ISSUE TITLE
Update CDK Pipelines instructions to use "main" instead of "master" branch

### ISSUE THREAD

**Issue by hakanson** [aws-samples/aws-cdk-intro-workshop#275]
### General Information
* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change 

### Description

Many git-based projects are using "main" instead of "master" for the primary branch.  Changing the workshop both aligns with that direction and add instructions how customers can use different branch names.

### Proposed Solution

My details relate to the .NET Workshop version, but there will be similar changes for each workshop language version.

This involves updating "Create Repository" instructions to use `main` as upstream, as well as adding a `Branch = "main"` parameter when creating the `CodeCommitSourceAction` in the sample code on both "Create New Pipeline" and "Add Application to Pipeline" instructions.

The local changes I had to make:

1) Update "Create Repository" instructions

https://github.com/aws-samples/aws-cdk-intro-workshop/blob/12962fcf4d1aa426d55adcafe9284fd1c0e56f6c/workshop/content/20-typescript/70-advanced-topics/200-pipelines/2000-create-repo.md#L67-L71

The comment should reference main instead of master and these git commands can be used:

```
git branch -m master main
git push --set-upstream origin main
```

2) Update "Create New Pipeline" instructions to add `Branch = "main"` under `new CodeCommitSourceActionProps` 

https://github.com/aws-samples/aws-cdk-intro-workshop/blob/8418d678bf54ba1de5d75c76f352d2ec6a9ab436/workshop/content/40-dotnet/70-advanced-topics/100-pipelines/3000-new-pipeline.md#L48-L55

3) Update "Add Application to Pipeline" instructions to add `Branch = "main"` under `new CodeCommitSourceActionProps` 

https://github.com/aws-samples/aws-cdk-intro-workshop/blob/8418d678bf54ba1de5d75c76f352d2ec6a9ab436/workshop/content/40-dotnet/70-advanced-topics/100-pipelines/4000-build-stage.md#L66-L73

4) Update this repos code for `PipelineStack.cs` to add `Branch = "main"` under `new CodeCommitSourceActionProps` 

https://github.com/aws-samples/aws-cdk-intro-workshop/blob/8418d678bf54ba1de5d75c76f352d2ec6a9ab436/code/csharp/pipelines-workshop/src/CdkWorkshop/PipelineStack.cs#L33-L39

### Environment

  - **CDK CLI Version:** 1.116.0 (build d04661d)
  - **Section:**  CDK Pipelines (Create Repository, Create New Pipeline, & Add Application to Pipeline)
  - **Browser:** all
  - **Language:** all

### Other information 

n/a

**Comment by ryparker** [comment]
Hey @hakanson  👋🏻 

Thanks for the feature request. I think it is a great idea to encourage the use of main > master in all workshops.

I'm going to mark this as p2 which means that we are unable to work on this immediately but we'd be happy to review a PR for this.

We use +1s to help prioritize our work, and if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) 🙏🏻

**Comment by peterwoodworth** [comment]
Thanks for the request again, we're going to fix this up real quick now 🙂
