### ISSUE TITLE
Incomplete cleanup / Cost trap

### ISSUE THREAD

**Issue by DC4JG** [aws-samples/aws-cdk-intro-workshop#276]
The workshop and CDK itself lack information about how to clean up correctly and which cost may occur.

As stated in #126 and ignored for years in https://github.com/aws/aws-cdk/issues/986, the user is left with a DynamoDB table, S3 bucket, CloudWatch logs and CloudFormation stack after finishing the workshop, without knowing about their existence.

This is a dark pattern (some may call it worse) as the user acts in good faith and in compliance with the cleanup section, yet will be left in an unclean state for redeployment and could be charged for resources he thought were destroyed.

I suggest the following steps:
- add a clear warning about potentially occurring costs (upfront, users may not complete the workshop)
- add description how/where to find an overview about all things which will/might create charges (e.g. in AWS Console)
- extend the code examples about information on the `RemovalPolicy` options
- implement and include the `cdk bootstrap --destroy` command

**Comment by ryparker** [comment]
Hey @DC4JG :wave: Thanks for bringing this up.

I agree that this could be confusing for new users and should be improved.

- add a clear warning about potentially occurring costs (upfront, users may not complete the workshop)
- add description how/where to find an overview about all things which will/might create charges (e.g. in AWS Console)

These would be a great first issue for anyone looking to contribute.

- extend the code examples about information on the RemovalPolicy options
- implement and include the cdk bootstrap --destroy command

These action items I believe could be their own issues/PRs and could be implemented after the others.

I'm marking this as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.
