### ISSUE TITLE
Windows installation steps wrong

### ISSUE THREAD

**Issue by PaulMaddox** [aws-samples/aws-cdk-intro-workshop#28]
When installing the CDK, the workshop recommends you install the CDK as Administrator on Windows. 

> Windows: you’ll need to run this as an Administrator

source: https://cdkworkshop.com/15-prerequisites/500-toolkit.html

This is incorrect - npm should be run as their normal user, otherwise the %PATH% does not get setup correctly, and `cdk` can't be run.

**Comment by NGL321** [comment]
I just ran through the full first stage of the CDK workshop on 32 and 64 bit Windows machines, and ran npm install as admin, and cdk *** as standard user, and I had no issues with permissions or PATH.
