### ISSUE TITLE
404 on conclusion page

### ISSUE THREAD

**Issue by PaulMaddox** [aws-samples/aws-cdk-intro-workshop#30]
This link 404's:
https://github.com/awslabs/aws-cdk/tree/master/examples

On this page:
https://cdkworkshop.com/70-conclusion.html

**Comment by electblake** [comment]
ee57007b6cc92dd0ba0fe937da5b4c590c063fdf fixes this, this should be marked as fixed

**Comment by NGL321** [comment]
Pages reworked and all links replaced.
Closing out!
