### ISSUE TITLE
Upgrade workshop content for CDKv2

### ISSUE THREAD

**Issue by njlynch** [aws-samples/aws-cdk-intro-workshop#308]
### General Information

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

The CDKv2 general availability release is upcoming. Shortly after releasing CDK v2.0.0, the CDK Workshop content should be updated to use and reference it.

### Proposed Solution

Update the deck and code, bit by bit. :)

- [x] Update [cdk-dynamo-table-viewer](https://github.com/cdklabs/cdk-dynamo-table-viewer) to v2 (@corymhall)
- [ ] Update Typescript `code` (code/typescript) & `workshop` content (workshop/content/20-typescript) (@corymhall)
- [ ] Update Python `code` (code/python) & `workshop` content (workshop/content/30-python) (@corymhall)
- [ ] Update Java `code` (code/java) & `workshop` content (workshop/content/50-java) (@corymhall)
- [ ] Update .NET `code` (code/csharp) & `workshop` content (workshop/content/40-dotnet) (@madeline-k)
- [x] Update prerequisites content (workshop/content/15-prerequisites) (@corymhall)

**Comment by madeline-k** [comment]
@corymhall is working on the typescript workshops.

**Comment by madeline-k** [comment]
I am going to start working on the dotnet workshop
