### ISSUE TITLE
Bad Python code for Add Application to Pipeline

### ISSUE THREAD

**Issue by jtgutt** [aws-samples/aws-cdk-intro-workshop#309]
Under [Python Workshop -> Advanced Topics -> CDK Pipelines -> Add Application to Pipeline](https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/4000-build-stage.html), the code provided for `pipeline_stage.py` is referring to a non-existent module `pypipworkshop_stack` and class `PypipworkshopStack`:

```
from aws_cdk import (
    core
)
from pypipworkshop_stack import PypipworkshopStack

class WorkshopPipelineStage(core.Stage):

    def __init__(self, scope: core.Construct, id: str, **kwargs):
        super().__init__(scope, id, **kwargs)

        service = PypipworkshopStack(self, 'WebService')
```

**Comment by wellsiau-aws** [comment]
what I consider as good working code is available here: https://github.com/aws-samples/aws-cdk-intro-workshop/tree/master/code/python/pipelines-workshop
