### ISSUE TITLE
Video intro

### ISSUE THREAD

**Issue by PaulMaddox** [aws-samples/aws-cdk-intro-workshop#31]
When delivering the workshop, and presenting the included deck - it gives a nice overview, and shows people the expected outcome.

For people discovering the workshop themselves, they don't get this. It would be good to record a 10min cut-down version of the deck and have it on the homepage.

**Comment by NGL321** [comment]
I think this is a good idea, I will look into it for the next release (maybe use demo from the Summit GA announcement)

**Comment by peterwoodworth** [comment]
Would be a good video opportunity for cdk construction zone to link here
