### ISSUE TITLE
Missing dependency causing pipeline build failure

### ISSUE THREAD

**Issue by jtgutt** [aws-samples/aws-cdk-intro-workshop#310]
After going through the steps given on [Python Workshop -> Advanced Topics -> CDK Pipelines -> Create New Pipeline](https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/3000-new-pipeline.html), my pipeline was failing to build, which was caused by `ImportError: cannot import name 'aws_codecommit' from 'aws_cdk' (unknown location)`.  I realized that I had to add that dependency, which was actually introduced on the previous [Create Repository](https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/2000-create-repo.html) page, along with the other 3 introduced on this page, to my `requirements.txt` file in order for the build to succeed:

```
-e .
pytest
aws-cdk.aws-codecommit==1.129.0
aws-cdk.aws-codepipeline==1.129.0
aws-cdk.aws-codepipeline-actions==1.129.0
aws-cdk.pipelines==1.129.0
```

**Comment by peterwoodworth** [comment]
This is a bug related to when the codebase was on cdk v1 - this is no longer the case so this should no longer be an issue 🙂
