### ISSUE TITLE
Documentation code typo

### ISSUE THREAD

**Issue by jewelsjacobs** [aws-samples/aws-cdk-intro-workshop#32]
In the workshop, on page / aliased link:

https://cdkworkshop.com/50-table-viewer/400-expose-table.html#now-we-can-access-the-table-from-our-stack the code sample has a typo that mismatches the constructor and super's arguments.

```
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, name, props);
```

**Comment by NGL321** [comment]
Fixed by #33
