### ISSUE TITLE
nodejsfunction for typescript workshop

### ISSUE THREAD

**Issue by josersleal** [aws-samples/aws-cdk-intro-workshop#322]
### General Information

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

The typescript/node should be done using nodejsfunction 

### Proposed Solution

nodejsfunction

**Comment by peterwoodworth** [comment]
Thanks for the request,

I'm not sure the existing example is something we want to replace, but there could be a way to do this in addition to the regular `Function`. This won't be something we'll be able to get to, but if someone submits a PR for it we could take a look at it 🙂

**Comment by peterwoodworth** [comment]
I don't think we should include this construct in the workshop
