### ISSUE TITLE
Workshop for testing only

### ISSUE THREAD

**Issue by josersleal** [aws-samples/aws-cdk-intro-workshop#323]
### General Information

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

testing is touched very lightly

### Proposed Solution

there should be a workshop just for testing to explain what is possible to do more extensibly or at least a reference to more information.

**Comment by peterwoodworth** [comment]
This seems a bit out of scope here - what exactly would you like to see out of a testing workshop?

This might belong better in the aws-cdk repo itself as a docs feature request if the scope of what you desire couldn't fit in our existing workshop.

Let me know, with as much detail as possible please!
