### ISSUE TITLE
Update Python Example for GA aws_cdk.pipelines

### ISSUE THREAD

**Issue by mbeacom** [aws-samples/aws-cdk-intro-workshop#347]
### General Information

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

The Python version of this workshop currently implemented the deprecated/developer interface `pipelines.CdkPipeline` as opposed to `pipelines.CodePipeline`.  This is out of alignment with the TypeScript version of the workshop and should be updated since `pipelines` went GA.

### Proposed Solution

Update python workshop code to use `pipelines.CodePipeline` as opposed to `pipelines.CdkPipeline`, matching logic to the TypeScript implementation.

### CDK CLI Version

1.134.0 (build dd5e12d)

### Section

pipelines-workshop

### Browser

all

### Language

Python

**Comment by peterwoodworth** [comment]
Thanks for the feature request! Seems this has been implemented already, check it out now!
