### ISSUE TITLE
cdk-dynamo-table-view dependency breaks Python Advanced Topics/CDK Pipelines module

### ISSUE THREAD

**Issue by awerchniak** [aws-samples/aws-cdk-intro-workshop#362]
### ModuleNotFoundError: No module named 'cdk_dynamo_table_view'

The code sample given in [these lines](https://github.com/aws-samples/aws-cdk-intro-workshop/blame/master/workshop/content/30-python/70-advanced-topics/200-pipelines/3000-new-pipeline.md#L36-L39) fails to install the [cdk-dynamo-table-viewer Construct](https://pypi.org/project/cdk-dynamo-table-viewer/) required to use the `TableViewer` dependency. This means that `cdk deploy` will fail in the next step as the dependency is missing.

### Reproduction Steps

Follow the tutorial as-is. I am using Ubuntu 20.04.3 on Windows Subsystem for Linux (WSL1), with Python 3.8.10. All other defaults are configured as given in the tutorial.

### Verbose Log

```
[Container] 2021/12/03 16:12:14 Running command cdk synth
--
Traceback (most recent call last):
File "/codebuild/output/src162005108/src/app.py", line 4, in <module>
from cdk_workshop.pipeline_stack import WorkshopPipelineStack
File "/codebuild/output/src162005108/src/cdk_workshop/pipeline_stack.py", line 7, in <module>
from cdk_workshop.pipeline_stage import WorkshopPipelineStage
File "/codebuild/output/src162005108/src/cdk_workshop/pipeline_stage.py", line 5, in <module>
from .cdk_workshop_stack import CdkWorkshopStack
File "/codebuild/output/src162005108/src/cdk_workshop/cdk_workshop_stack.py", line 8, in <module>
from cdk_dynamo_table_view import TableViewer
ModuleNotFoundError: No module named 'cdk_dynamo_table_view'
Subprocess exited with error 1
```

### CDK CLI Version

2.0.0

### Section

Advanced Topics/CDK Pipelines

### Browser

Chrome

### Language

Python

**Comment by awerchniak** [comment]
I attempted to remedy this by including an additional `pip install cdk-dynamo-table-viewer` line, but unfortunately this did not fix the problem, as it results in the following error in the logs from the Build step:
```
[Container] 2021/12/03 16:21:42 Running command cdk synth
--
Traceback (most recent call last):
File "/codebuild/output/src905320542/src/app.py", line 3, in <module>
import aws_cdk as cdk
File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/aws_cdk/__init__.py", line 21457, in <module>
from . import aws_apigateway
File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/aws_cdk/aws_apigateway/__init__.py", line 620, in <module>
import aws_cdk.aws_certificatemanager
File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/aws_cdk/aws_certificatemanager/__init__.py", line 103, in <module>
import aws_cdk.aws_cloudformation
File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/aws_cdk/aws_cloudformation/__init__.py", line 124, in <module>
import aws_cdk.aws_iam
File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/aws_cdk/aws_iam/__init__.py", line 238, in <module>
import aws_cdk.core
File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/aws_cdk/core/__init__.py", line 1692, in <module>
class ConstructNode(metaclass=jsii.JSIIMeta, jsii_type="@aws-cdk/core.ConstructNode"):
File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/aws_cdk/core/__init__.py", line 1713, in ConstructNode
def synth(cls, root: "ConstructNode", *, outdir: typing.Optional[str]=None, skip_validation: typing.Optional[bool]=None, runtime_info: typing.Optional[aws_cdk.cx_api.RuntimeInfo]=None) -> aws_cdk.cx_api.CloudAssembly:
AttributeError: partially initialized module 'aws_cdk' has no attribute 'cx_api' (most likely due to a circular import)
Subprocess exited with error 1
```

I noticed in the stack trace that the build environment is using Python3.9, and according to https://pypi.org/project/cdk-dynamo-table-viewer/ the TableViewer only supports up to 3.8, so I made the following changes to use a python3.8 virtual environment:
```
pipeline = pipelines.CodePipeline(
    self,
    "Pipeline",
    synth=pipelines.ShellStep(
        "Synth",
        input=pipelines.CodePipelineSource.code_commit(repo, "master"),
        commands=[
            "npm install -g aws-cdk",  # Installs the cdk cli on Codebuild
            "apt update && apt install -y python3.8-venv", # Install python3.8 virtual environment
            "python3.8 -m venv env && . ./env/bin/activate",  # Create python 3.8 virtual env and activate
            "pip install -r requirements.txt",  # Instructs Codebuild to install required packages
            "pip install cdk-dynamo-table-viewer",  # Installs TableViewer on CodeBuild
            "cdk synth",
        ]
    ),
)
```

Unfortunately, this didn't fix the problem and the same error occurs in python3.8. I was able to continue the tutorial by just commenting out that dependency, but this means that the TableViewer (and associated pipeline tests) are omitted in the result.

**Comment by awerchniak** [comment]
I realized what the issue was with my above comment; I was installing the wrong version of `cdk-dynamo-table-viewer`. This is called out in the "Install" page of the "Using Construct Libraries" chapter (see https://github.com/aws-samples/aws-cdk-intro-workshop/blob/master/workshop/content/30-python/50-table-viewer/200-install.md).

I tried again while using the correct install syntax and it worked. I will issue a PR with the changes to fix the demo.

**Comment by awerchniak** [comment]
Addressed in https://github.com/aws-samples/aws-cdk-intro-workshop/pull/363

**Comment by NGL321** [comment]
Thanks for submitting this @awerchniak! I will take a look and review your PR tomorrow.

**Comment by awerchniak** [comment]
Thanks @NGL321 ! Have you gotten a chance to look at it yet?

**Comment by jsphwllng** [comment]
Further here: #383

**Comment by peterwoodworth** [comment]
Posting here as well in case PR closes -

I am not sure how installing the dependency directly through the CLI rather than through requirements.txt is causing a failure for you - I'm unable to reproduce what you're seeing, so I'm not convinced this is necessary. Is there something I missed maybe
