### ISSUE TITLE
Cloud9 setup section

### ISSUE THREAD

**Issue by shinglyu** [aws-samples/aws-cdk-intro-workshop#366]
### General Information

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

Currently Cloud9 by default provide `cdk` version `1.134.0`. Upgrading it to v2 using `npm update -g aws-cdk` will mess up the NVM path and make the `cdk` command unusable. 

My workaround right now is to do `nvm install node && npm install aws-cdk && npx cdk --version`

### Proposed Solution

It would be great to have an official guidance on how to setup CDK v2 in Cloud9. 

### CDK CLI Version

2.0.0

### Section

Prerequsites

### Browser

all

### Language

all

**Comment by peterwoodworth** [comment]
I think this is a bit out of scope of the workshop. But we'd love to have documentation somewhere about this. Could you open this issue in the `aws-cdk` repository if you're still interested in us having official guidance on this? Thanks.
