### ISSUE TITLE
Typescript workshop import error in lib/hitcounter.ts

### ISSUE THREAD

**Issue by Osama-Rashid** [aws-samples/aws-cdk-intro-workshop#382]
### What is the problem?

In typescript's main workshop, there is an import error in the file **_hitcounter.ts_** under the **_lib_** folder. Import of **_Construct_** class is being done from **_constructs_** however it should be done from **_@aws-cdk/core_** (the former is causing the below mentioned error).

![image](https://user-images.githubusercontent.com/40798025/146814408-291b9b05-348c-44b7-a134-7c53d2851be7.png)

### Reproduction Steps

Following the workshop instructions, if you use the import command: **_import { Construct } from 'constructs'_**, then it should reproduce the error.

### CDK CLI Version

1.123.0 (build fad855e)

### Section

Typescript

### Browser

Chrome

### Language

TypeScript

**Comment by peterwoodworth** [comment]
Our workshop was updated for CDK V2. The `core` method you're describing is for V1, while importing for `constructs` is for v2. Please start the workshop over from V2 and see if you still run into issue here.
