### ISSUE TITLE
Cookie bar pops up every time

### ISSUE THREAD

**Issue by ghost23** [aws-samples/aws-cdk-intro-workshop#394]
### What is the problem?

I cannot get rid of the cookie preference snackbar at the bottom of the page. It always pops back up after a page change, no matter what I choose in terms of accepting cookies.

### Reproduction Steps

I am using chrome on Windows 10 with my ad blocker turned off. I visit https://cdkworkshop.com/ and I see the cookies preference snackbar at the bottom of the page.
I either accept some or all of the cookies (could not notice a difference) and hit "Save preferences" (or Accept all, again, makes no difference in what follows).
I reload the page, or simply navigate to another page within the workshop.
I see the cookie snackbar again. I can do this multiple times without a different outcome.

**Comment by NGL321** [comment]
Hmm, I can confirm this. Thank you for reporting! Since it isnt functionally breaking the workshop, its a slightly lower priority, but it will certainly be addressed

**Comment by HeskethGD** [comment]
I just duplicated this bug report by mistake. It is breaking the workshop, it covers half the screen and makes it unusable

**Comment by dcheng** [comment]
Please fix this. The site is unusable as it is....

**Comment by HeskethGD** [comment]
Is there any update on this?

**Comment by peterwoodworth** [comment]
Thanks for posting this @ghost23,

I know you posted this first, but I'm going to close this in favor of #427. Please take any discussion there 🙂
