### ISSUE TITLE
(docs):The construct name is wrongly referred in https://cdkworkshop.com/30-python/50-table-viewer/300-add.html

### ISSUE THREAD

**Issue by spraja08** [aws-samples/aws-cdk-intro-workshop#414]
### What is the problem?

Page URL - https://cdkworkshop.com/30-python/50-table-viewer/300-add.html

In the code snippet shown the following line 

`from cdk_dynamo_table_viewer import TableViewer
`
shall be changed to

`from cdk_dynamo_table_view import TableViewer
`

### Reproduction Steps

Not any different from the steps in the workshop

**Comment by ryparker** [comment]
Hey @spraja08 👋🏻 Thanks for reporting this.

A dev will pick up this bug in order of priority. This is marked as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.
