### ISSUE TITLE
possibility of adding a CDK REPL to the workshop

### ISSUE THREAD

**Issue by 3p3r** [aws-samples/aws-cdk-intro-workshop#426]
### General Information

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Description

Hello! I am the author of [cdk-web](https://www.npmjs.com/package/cdk-web). I was wondering if adding a REPL-like feature to the workshop would be beneficial and wanted to gauge your interest.

If there's enough interest, I'll implement and open up a PR.

### Proposed Solution

Using [cdk-web](https://www.npmjs.com/package/cdk-web) to implement a REPL-like feature like the one here: https://3p3r.github.io/cdk-web/

**Comment by mrpackethead** [comment]
This is a great idea. :-) My +1

**Comment by 3p3r** [comment]
I just updated the playground: https://3p3r.github.io/cdk-web/
This is very close to what a REPL would look like.

performance is OK-ish. my iPhone and my desktop can take it but I have a VM setup for work and it struggles in that.
there is also possibility of putting cdk web in a web worker to keep the page responsive.

**Comment by peterwoodworth** [comment]
Something like this would be _super cool_ if implemented well. If you're still interested in implementing this @3p3r, I'd love to see what you come up with

**Comment by 3p3r** [comment]
my offer is still on the table!

I am thinking, to create a shell like experience, we need to mix in XtermJS and something like [Cash](https://github.com/dthree/cash/) to provide basic commands like `cd` and `grep` and stuff like that.

I've already made this bridge: https://github.com/3p3r/cash-money

then it's just a matter of how do we style it for the website.

if I can sit down with maintainers of the workshop maybe for half an hour I think we can come up with something exciting.

**Comment by peterwoodworth** [comment]
Wonderful to hear @3p3r !

I'll coordinate with the team once the work week begins and then reach out to you
