### ISSUE TITLE
Use newer version of cdk-dynamo-table-viewer

### ISSUE THREAD

**Issue by gmarchiny** [aws-samples/aws-cdk-intro-workshop#45]
When going through the CDK workshop, I noticed the referenced version of cdk-dynamo-table-viewer (3.0.2) has an earlier release of the CDK core, which causes compilation issues when going through this workshop with the newest version (1.0.0) of the CDK core. Here's the page where the `npm install` command is mentioned: 

https://cdkworkshop.com/20-typescript/50-table-viewer/200-install.html

For me, using 3.0.5 of the table viewer made this issue go away: 

```
npm install cdk-dynamo-table-viewer@3.0.5
```

**Comment by eladb** [comment]
We should be able to omit the explicit version number now that we are in 1.0.0

**Comment by abhishek03joshi** [comment]
@eladb This issue comes back for "cdk-dynamo-table-viewer" 3.1.2 with aws-cdk version 1.35.0 while doing the typescript CDK workshop.
