### ISSUE TITLE
Test is not throwing error

### ISSUE THREAD

**Issue by rushikeshkoli** [aws-samples/aws-cdk-intro-workshop#456]
### What is the problem?

'read capacity can be configured' test is not failing when I change the readCapacity params to more than 20. Can you confirm this please?

### Reproduction Steps

```ts
test('read capacity can be configured', () => {
  const stack = new cdk.Stack();

  expect(() => {
    new HitCounter(stack, 'MyTestConstruct', {
      downstream:  new lambda.Function(stack, 'TestFunction', {
        runtime: lambda.Runtime.NODEJS_14_X,
        handler: 'hello.handler',
        code: lambda.Code.fromAsset('lambda')
      }),
      readCapacity: 30
    });
  }).toThrowError(/readCapacity must be greater than 5 and less than 20/);
});
```

**Comment by peterwoodworth** [comment]
Did you make sure to follow the steps on this page prior to that? These steps should properly setup your HitCounter construct such that it will throw this error. https://cdkworkshop.com/20-typescript/70-advanced-topics/100-construct-testing/2000-validation-tests.html
