### ISSUE TITLE
Incorrect Lambda handler reference in Hitcounter construct (Python)

### ISSUE THREAD

**Issue by dennydaugherty** [aws-samples/aws-cdk-intro-workshop#463]
### What is the problem?

There is an error in the code for the HitCounter construct that references the Lambda handler. It should be `self._handler` and not `self.handler`

### Reproduction Steps

Follow the CDK workshop through the step "Granting Permissions"

**Comment by peterwoodworth** [comment]
Reviewing now, thanks for your patience 🙂
