### ISSUE TITLE
Items found in review of Python version of CDK Workshop

### ISSUE THREAD

**Issue by Jerry-AWS** [aws-samples/aws-cdk-intro-workshop#47]
Let me know if you'd like me to break these up into separate issues. It was easier to just track them in one place while doing the review. A couple of these aren't issues with the Workshop but rather things in the `cdk` tool.

~~0.	Why don’t the code snippets have a light/dark toggle like in the Dev Guide?  :-)~~
~~1.	On Windows, the output of `cdk init` is full of terminal codes that would produce color and boldface on a linux system, but here make the output almost unreadable. Screen shot attached.
![codes_exposed](https://user-images.githubusercontent.com/52084730/61986076-5ddfae80-afc1-11e9-8d7e-b9e71aa6947c.png)~~
~~Not a problem in the Workshop per se of course. The color works fine when doing other things with the CDK, oddly.~~
~~2.	Missing prerequisite: On Windows, Python needs to be installed so it’s on the `PATH`. Unfortunately, this is not the default! (It’s a checkbox on the first page of the Windows installer.) Without Python on the `PATH`, `cdk init` won’t create a virtualenv, which then throws off a lot of things...~~
~~3.	I noticed that the `cdk init` output says that the CDK expects a Python executable named `python3`. The Windows Python installer does not install such an executable. Fortunately `cdk init` seems to work regardless as long as Python's on the path; however, this text should probably be changed. On Windows there’s a launcher called `py` that gets installed in `C:\Windows` so it’s guaranteed to be on the `PATH`. It is responsible for reading shebang lines from executed scripts (since Windows doesn’t do that natively) and launching the specified Python executable, among other things. So on Windows maybe just use that. Then you don’t have to worry about the interpreter being on the `PATH`.~~
~~4.	The command given to activate the virtualenv on Windows uses the wrong slashes. Normally Windows is happy to use forward slashes in paths; however, when specifying an executable, it looks like you must use backslashes. `.env\scripts\activate.bat` will work.~~
~~5.	I’m noticing that a lot of the `cdk` screenshots are a lot less colorful than the cdk actually is. Haas the `cdk` tool been upgraded recently to be more colorful? Maybe update the screen shots.  :-) Whoops, those aren't screen shots. The syntax coloring should be turned off for those snippets, or else screen shots should be used if the color is important.~~
~~6.	The API Gateway topic tells you to put some code in, but it doesn’t say which file it goes in. `hello_stack.py` is the last file you were working on in the previous topic and it does indeed go in there, but it would be nice to mention that.~~
~~7.	In the Hit Counter Handler topic, the highlighted code (that indicates the lines you need to add to `hitcounter.py`) does not include the function definition for the `handler()` method (and its `@property` decorator), which does need to be added.~~
~~ 8.	The Use The Hit Counter topic instructs you to open `lib/cdk-workshop-stack.ts`, which doesn’t exist in this Python project. It should be `hello/hello_stack.py`. ~~
9. Also, the imports in the new version of this code are in a different order than the original code you’re modifying. They work fine but it may throw readers off if their file is even slightly different from the one you think they have.
9.	In the Cloudwatch Logs topic, users are instructed to click **View On CloudWatch Logs**, but the actual name of the button is **View Logs in CloudWatch** (it’s shown in the screen shot).
10.	In Granting Permissions, you’re told to add the “highlighted lines” to `hitcounter.py`. There’s only one line highlighted. (Only one line is in fact needed; the plural in the text is wrong.)
11.	At the end of the Test the Hit Counter topic, we’re told we’ll next consume a construct library published in npm. That's for Node.js; this should say PyPI.
12.	In the Installing the Library topic, output is given for `pip install` command. There’s actually a lot more output; it should indicate that these are only the last two lines of the output (e.g. with an ellipsis).
~~13.	In Add the Table Viewer to Your App topic, you’re told to edit `lib/cdk-workshop-stack.ts`. This should be `hello/hello_stack.py`.~~
~~14.	In the Exposing Our Hit Counter Table topic, you’re told to edit `hitcounter.ts`. This should be `hello/hitcounter.py`.~~
~~15.	The code in this topic changes `table = ddb.Table( to self._table`. Similarly, the `‘HITS_TABLE_NAME’` definition should be changed to `self.table.table_name`, and.`table.grant_read_write_data` needs to be changed to `self.table`. These changes are in the code but aren’t highlighted as changes. They should be highlighted so users know to make them.~~
16.	The tip in the topic suggests holding down the Control or Command key and clicking on `TableViewer` to see the source code for its definition. This will depend on the editor you’re using, probably? Maybe say “in many editors (we use VS Code)” or something similar.
~~17.	I noticed that when selecting text in the code blocks, the selection is invisible in Firefox. This is annoying. Also, selection works fine in dark mode in the CDK Dev Guide, so not sure why it doesn't work right here. (Works OK in Chrome and Edge, though.) ~~

**Comment by stevenbryen** [comment]
@Jerry-AWS FYI I have raised some Pull Requests to fix a few of the changes you have listed above. Specifically the references to TypeScript files and the additional lines that needed highlighting in your point 16. 

There are a lot of points here, I would encourage you to also raise some PRs if you want to suggest a change to anything else in the docs. The simplest way is to do this via the Github website by just pressing the pencil icon to edit the file in question. It's the best way to demonstrate a specific change to the maintainer as it will show the diff.

**Comment by Jerry-AWS** [comment]
@stevenbryen I'll put together some PRs for some of these.

**Comment by Jerry-AWS** [comment]
I've crossed out some of the items in my original report. Some of them because they're cosmetic, others because they are not bugs in the Workshop (I've reported them against the CDK), and of course the ones you already submitted PRs for them. I'm going to work on PRs for the rest.

**Comment by Jerry-AWS** [comment]
@stevenbryen I've put together PRs for most of the items I found. Please let me know when these get merged and posted and I'll run through the workshop again.
