### ISSUE TITLE
cdkworkshop python dynamodb table will not incr. 

### ISSUE THREAD

**Issue by rhtaylor** [aws-samples/aws-cdk-intro-workshop#494]
### Describe the bug

I when through the tutorial and reprodusing the code as it is listed (with the adjustment for the bug that is listed on another thread "_handler not hander"). The deploy works and looks good. However the dynamodb table never increments the counter as in the guide. I do not know where the issue is. The guild illustrates the counter has being over 0. In my console it is always 0. I have gone over this twice now

### Expected Behavior

they table will have the item increment wen you hit the api gateway endpoint. 

### Current Behavior

The dynamodb table never increments. 

### Reproduction Steps

You do exactly as the tutorial directs. You have to replace cdk_workshop/hitcounter.py's self.handler with self._handler. Then when you are complete you either curl the endpoint or hit the endpoint in the browser. The dynamoDB console should have the incremented number of hits as over 0. 

### Possible Solution

It is possible the tutorial has code that was miswritten as the _handler is written as hander. 

### CDK CLI Version

2.20.0

### Section

https://cdkworkshop.com/30-python/40-hit-counter/700-test.html

### Browser

chrome

### Language

python

**Comment by peterwoodworth** [comment]
We have fixed the `_handler` `handler` typo. Please check again and see if you are still running into errors 🙂
