### ISSUE TITLE
Include `!**/lambda/*.js` in `.gitignore` by default

### ISSUE THREAD

**Issue by zachgoll** [aws-samples/aws-cdk-intro-workshop#502]
### General Information

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

While going through the [CDK Pipelines](https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines.html) portion of the workshop, if you have not updated the `.gitignore` file, your pipeline will fail because the lambda assets will not be discoverable from the build output:

![image](https://user-images.githubusercontent.com/16676157/165291156-019e5b3d-40b1-4455-9f7a-1af933315e2f.png)

When initially creating the lambda function, the tutorial mentions, "Also, if you are going to actively use git, consider adding !lambda/*.js in .gitignore file." ([source](https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html))

I think it would be a nice default to *not* ignore the lambda code as it breaks the remainder of the workshop and is pretty easy to miss.

### Proposed Solution

I think there are 2 possible improvements:

1. Include the line `!**/lambda/*.js` in the `.gitignore` by default - even if the user does not follow the CDK Pipelines portion of the tutorial, this doesn't hurt to have in there.
2. Or... Update [this page](https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html) to be more descriptive as to *why* you need to add this snippet (when I first read through, I totally missed that the `.gitignore` by default ignored JS files).  Proposed below:

![image](https://user-images.githubusercontent.com/16676157/165292979-bac54ac0-e55c-489b-9ba7-7beb0965f23c.png)

Overall, very small changes, but would have saved me a couple hours and I think it could do the same for future viewers of this tutorial!

### CDK CLI Version

2.21.1

### Section

CDK Pipelines

### Browser

Chrome

### Language

TypeScript

**Comment by peterwoodworth** [comment]
The [Java](https://cdkworkshop.com/50-java/30-hello-cdk/200-lambda.html) and [.NET](https://cdkworkshop.com/40-dotnet/30-hello-cdk/200-lambda.html) workshops also don't mention this when they use the same lambda function and location.

A note in each of these sections explaining why we want this in the `.gitignore` would be great! Thanks for calling this out 🙂
