### ISSUE TITLE
Fix incorrectly highlighted line of code

### ISSUE THREAD

**Issue by jlipe** [aws-samples/aws-cdk-intro-workshop#552]
### Describe the bug

In 'Typescript' > 'Advanced Topics' > 'Pipelines' > 'Build Stage', there is a highlighted line of code in line 68 of the file. This line was unchanged from the previous file in the module  'Typescript' > 'Advanced Topics' > 'Pipelines' > 'New Pipeline' on line 28 of that file.

### Expected Behavior

There wouldn't be a highlighted line of code in the 'Build Stage' file because it was unchanged from the previous code.

### Current Behavior

There is a highlighted line of code that was unchanged.

### Reproduction Steps

Look at the line of code `const pipeline = new CodePipeline(this, 'Pipeline', {` in "4000-build-stage" and compare it to the same line in "3000-new-pipeline".

**Comment by peterwoodworth** [comment]
Yup, thanks for reporting this!
