### ISSUE TITLE
Python Pipelines: Incorrect referencing

### ISSUE THREAD

**Issue by kaizio** [aws-samples/aws-cdk-intro-workshop#559]
### Describe the bug

On this page (https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/1000-setting-up.html) in the first code snippet the line:

from pipeline_stage import WorkshopPipelineStage

should be:
from cdk_workshop.pipeline_stage import WorkshopPipelineStage 

as it is seen on https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/3000-new-pipeline.html

The lines is also missing from https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/2000-create-repo.html

### Expected Behavior

For cdk synth to compile

### Current Behavior

cdk synth is not able to find the module.

### Reproduction Steps

Use the following for the pipeline_stack.py

from pipeline_stage import WorkshopPipelineStage

try to run cdk synth.

### Language

Python

**Comment by peterwoodworth** [comment]
addressed in pr linked
