### ISSUE TITLE
Highlighting in Typescript and .NET workshops is incorrect

### ISSUE THREAD

**Issue by justindho** [aws-samples/aws-cdk-intro-workshop#585]
### Describe the bug

Highlighting in Typescript and .NET workshops is incorrect ("Polish Pipeline" steps".

### Expected Behavior

Correctly highlighted lines in workshop.

### Current Behavior

Incorrectly highlighted lines in workshop.

### Reproduction Steps

View
* https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.html
* https://cdkworkshop.com/40-dotnet/70-advanced-topics/100-pipelines/5000-test-actions.html

### Possible Solution

#586

**Comment by peterwoodworth** [comment]
Thanks for calling this out and making a PR!
