### ISSUE TITLE
'AWS CDK Reference' link at end of cdkworkshop.com page gives a 404 error

### ISSUE THREAD

**Issue by rnusser** [aws-samples/aws-cdk-intro-workshop#59]
### What is the problem?
Trying to follow the link for 'AWS CDK Reference'  at the end of the main page on https://cdkworkshop.com/ gives a 404 Error. 

The current link is https://awslabs.github.io/aws-cdk/

### Other information 
Perhaps the link should be https://docs.aws.amazon.com/cdk/api/latest/docs/aws-construct-library.html

**Comment by Jerry-AWS** [comment]
This appears to have been fixed.

**Comment by javydekoning** [comment]
@eladb this can be closed, the current link is correct.
