### ISSUE TITLE
cdkworkshop.com asks "Select your cookie preferences" on every page regardless of being already accepted.

### ISSUE THREAD

**Issue by yuyokk** [aws-samples/aws-cdk-intro-workshop#661]
### Describe the bug

Hi team,

I need to accept cookies on each screen :( 

<img width="1364" alt="Screenshot 2022-09-09 at 13 02 35" src="https://user-images.githubusercontent.com/1225343/189336301-ee135d57-075d-49a8-b2d8-6ab7f06492c4.png">

### Expected Behavior

Notifcation should not appear on next page after clicking "Accept all".

### Current Behavior

I see "Select your cookie preferences" on each page even after clicking "Accept all"

### Reproduction Steps

1. Go to https://cdkworkshop.com/
2. Click "Accept all"
3. Click on "next" arrow 

Expected behaviour:

No cookie preferences popup

Actual result:

![image](https://user-images.githubusercontent.com/1225343/189336920-d3763901-7cdf-40ac-9fa7-8271d32977e5.png)

**Comment by peterwoodworth** [comment]
@yuyokk what browser are you using? Do you have any special settings enabled we might need to know about? I can't get this banner to show at all

**Comment by yuyokk** [comment]
@peterwoodworth it is same behaviour on Firefox, Chrome and Safari for me.

**Comment by pmgledhill102** [comment]
I also have the same problem across both a Win 11 PC running Chrome or Edge. I also get it using Safari or Chrome on an iPhone.

I made a quick phone video of the issue. I tried playing with the Customize settings, but still doesn't remember.

https://youtube.com/shorts/BEuNR5vxXbI?feature=share

**Comment by indrora** [comment]
If this is still an issue after 2023, please open a new ticket.
