### ISSUE TITLE
WorkshopPipeline fails to install dotnet-sdk-3.1

### ISSUE THREAD

**Issue by joseph-suchar-modmed** [aws-samples/aws-cdk-intro-workshop#693]
### Describe the bug

THE .NET WORKSHOP -> CREATE NEW PIPELINE

When the pipeline runs on AWS, you get the following error:

`[Container] 2022/09/28 02:16:54 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sudo apt-get install -y dotnet-sdk-3.1. Reason: exit status 100`

[log-events-viewer-result.csv](https://github.com/aws-samples/aws-cdk-intro-workshop/files/9660896/log-events-viewer-result.csv)

### Expected Behavior

For the pipeline to execute successfully

### Current Behavior

`[Container] 2022/09/28 02:16:54 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sudo apt-get install -y dotnet-sdk-3.1. Reason: exit status 100`

### Reproduction Steps

Follow [https://cdkworkshop.com/40-dotnet/70-advanced-topics/100-pipelines/3000-new-pipeline.html](https://cdkworkshop.com/40-dotnet/70-advanced-topics/100-pipelines/3000-new-pipeline.html)

**Comment by ubaidullah-r** [comment]
yes i found this as well, I found below workaround 
"npm install -g aws-cdk",
"wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-Microsoft-prod.deb",
"sudo dpkg -i packages-Microsoft-prod.deb",
  "sudo apt-get update",
  "sudo apt-get install -y dotnet-sdk-3.1",
   "cd src",

 "dotnet build", // Language-specific build cmd
  "cd ..",
 "npx cdk synth"
note: you can follow my repository as well it has working code of all workshop 
repo-link:https://github.com/ubaidullah-r/dot-net-aws-cdk
