### ISSUE TITLE
Workshop does not talk about IAM set up

### ISSUE THREAD

**Issue by gopinaath** [aws-samples/aws-cdk-intro-workshop#751]
### Describe the bug

This section provides description of getting Git credentials for the IAM user.  
https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/2000-create-repo.html

It states "_To do this, go to the [IAM Console](https://console.aws.amazon.com/iam), then navigate to Users and then your user of choice._"

### Expected Behavior

This section provides description of getting Git credentials for the IAM user.  
https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/2000-create-repo.html

It states "_To do this, go to the [IAM Console](https://console.aws.amazon.com/iam), then navigate to Users and then your user of choice._"

It should talk about how to set up IAM role and/or policy required for this IAM user.  Not doing so will result in "`fatal: unable to access 'https://git-codecommit.geo-region-number.amazonaws.com/v1/repos/XXX/': The requested URL returned error: 403`"

### Current Behavior

Following the instructions without taking care of IAM role/policy results in fatal error. `.../WorkshopRepo/': The requested URL returned error: 403`

### Reproduction Steps

Follow the steps as given in "https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/2000-create-repo.html" and try to do `git push --set-upstream origin main`

### CDK CLI Version

2.49.0 (build 793dd76)

### Section

https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/2000-create-repo.html

### Browser

all

### Language

Python

**Comment by peterwoodworth** [comment]
This should be covered on our [prerequisites](https://cdkworkshop.com/15-prerequisites/200-account.html) page. Is there anything not found here that you think should be added?
