### ISSUE TITLE
[Japanese page] git remote add branch should be main, not master.

### ISSUE THREAD

**Issue by yt03sakamo** [aws-samples/aws-cdk-intro-workshop#764]
### Describe the bug

The description of git remote add to codecommit specifies master as the branch, which is not appropriate.
This is because if you create a branch in git without specifying anything, the branch name will be main.
When you run it, an error occurs and you cannot proceed with the procedure.
The branch name has been main since October 2020, so users who have been using git since before then may not encounter this problem.

### Expected Behavior

Being able to proceed to the next step once the command has been specified and typed.

### Current Behavior

The following error occurred when I followed the steps described.

The following error occurs because the branch name in git is main.

error: src refspec master does not match any

### Reproduction Steps

No code to be submitted due to text correction request.

### Possible Solution

Can you change the shell or annotate the shell?

### Additional Information/Context

In the English documentation, the branch name is main, but the Japanese documentation is master.

**Comment by stefanfreitag** [comment]
Hi @indrora, if you are fine I would try to come up with a PR.

I think there needs to be also a change to the image for the english and japanese versions

* https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/repo-code.png
* https://cdkworkshop.com/ja/20-typescript/70-advanced-topics/200-pipelines/repo-code.png

In the image also "master" in mentioned in the drop down for the branches.
