### ISSUE TITLE
[Japanese/Python] WorkshopPipeline fails to execute

### ISSUE THREAD

**Issue by 3socha** [aws-samples/aws-cdk-intro-workshop#772]
### Describe the bug

WorkshopPipelineStack (CodePipeline) execution fails.

### Expected Behavior

WorkshopPipelineStack runs successfully.

### Current Behavior

The following error occurred during the CodeBuild.

```
[Container] 2022/11/16 07:56:02 Running command cdk synth
Traceback (most recent call last):
  File "/codebuild/output/src486291841/src/app.py", line 6, in <module>
    from cdk_workshop.pipeline_stack import WorkshopPipelineStack
  File "/codebuild/output/src486291841/src/cdk_workshop/pipeline_stack.py", line 8, in <module>
    from pipeline_stage import WorkshopPipelineStage
ModuleNotFoundError: No module named 'pipeline_stage'

Subprocess exited with error 1
```

### Reproduction Steps

This occurs when the Japanese version of the procedure is performed.
It does not occur in the English version.

### Possible Solution

Modify the following to match the English version.

```diff
  from constructs import Construct
  from aws_cdk import (
      Stack,
      aws_codecommit as codecommit,
      pipelines as pipelines,
  )
- from pipeline_stage import WorkshopPipelineStage
+ from cdk_workshop.pipeline_stage import WorkshopPipelineStage

  class WorkshopPipelineStack(Stack):
```

### CDK CLI Version

2.50.0 (build 4c11af6)

### Section

Advanced Topics / CDK Pipelines / Add Application to Pipeline (Japanese)

### Browser

Chrome

### Language

Python

**Comment by peterwoodworth** [comment]
Thanks for reporting this, and for the PR 🙂
