### ISSUE TITLE
Indentation is missing in "Lambda handler code" of "Hello Lambda"

### ISSUE THREAD

**Issue by trivikr** [aws-samples/aws-cdk-intro-workshop#79]
### What is the problem?
* Indentation is missing in "Lambda handler code" of "Hello Lambda"
  * Link: https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html

![indentation-missing-lambda-handler](https://user-images.githubusercontent.com/16024985/65973257-de86b500-e41f-11e9-92bc-d1d26cb173fb.png)

* Indentation is present in "Cleaup sample" though
  * Link: https://cdkworkshop.com/20-typescript/30-hello-cdk/100-cleanup.html

![indentation-present-cleanup-sample](https://user-images.githubusercontent.com/16024985/65973347-06761880-e420-11e9-944a-ce576b570827.png)

### Reproduction Steps
Visit https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html

### Verbose Log
N/A

### Environment

N/A

**Comment by javydekoning** [comment]
Looks like an issue in Hugo to me. The markdown is correct but when the code is after a list it is rendered incorrectly. I'll add a horizontal rule to circumvent this.
