### ISSUE TITLE
Japanese Screenshot on TypeScript Polish Pipeline Page

### ISSUE THREAD

**Issue by BelphegorPrime** [aws-samples/aws-cdk-intro-workshop#804]
### Describe the bug

on the https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.html page is a screenshot where the language is in japanese(?)

### Expected Behavior

Language in the Screenshot should be same as the selected language.

### Current Behavior

Japanese Text in Screenshot

### Reproduction Steps

goto https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines/5000-test-actions.html  page scroll down a little bit to the first screenshot with the source "./stack-outputs.png"

### Browser

Chrome

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this!
