### ISSUE TITLE
Explore gatsbyjs instead of hugo for building website?

### ISSUE THREAD

**Issue by trivikr** [aws-samples/aws-cdk-intro-workshop#81]
### General Information
* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change 

### Description
* First of all, thank you for setting up this amazing website https://cdkworkshop.com for helping people learn about CDK. We're considering doing similar tutorials for [aws-sdk-js-v3-workshop](https://github.com/aws-samples/aws-sdk-js-v3-workshop) after v3 goes GA
* As per your [developer guide](https://github.com/aws-samples/aws-cdk-intro-workshop#developer-guide), your website is built in [hugo](https://gohugo.io/) which is written in golang. I noticed that [aws-cdk](https://github.com/aws/aws-cdk) itself is written in TypeScript/JavaScript. I was wondering if you'd explored something JavaScripty like [GatsbyJS](https://www.gatsbyjs.org/) for building website for this workshop. 

### Proposed Solution
Explore something JavaScripty like [GatsbyJS](https://www.gatsbyjs.org/) for building website for this workshop.

### Environment
N/A

### Other information 
N/A

**Comment by NGL321** [comment]
This is a good idea, unfortunately it would be a lot of effort to switch over due to the formatting requirements.
I'm going to put a pin in this to investigate later.

**Comment by peterwoodworth** [comment]
I'm sorry, but we won't be looking into implementing this anymore. If you'd still like to see this, please submit a new feature request with explanation for why you'd like to have this. Thanks!
