### ISSUE TITLE
Syntax error in DynamoDB example.

### ISSUE THREAD

**Issue by javydekoning** [aws-samples/aws-cdk-intro-workshop#83]
### What is the problem?

Section `Exposing our hit counter table` has a syntax error:

```ts
    const table = new dynamodb.Table(this, 'Hits', { 
      name: 'path', 
      type: dynamodb.AttributeType.STRING
    });
```

These are not the correct properties, should be wrapped in `partitionKey: {}`

**Comment by eladb** [comment]
should be fixed by https://github.com/aws/aws-cdk/pull/4552
