### ISSUE TITLE
Cannot import the HitCounter Module

### ISSUE THREAD

**Issue by Amanda-Ruzza** [aws-samples/aws-cdk-intro-workshop#852]
### Describe the bug

I'm encountering an issue with downloading the ``hitcounter module`` on the workshop.
I looked at previous (closed) tickets, and tried to troubleshoot it that way, however, it seems that the module does NOT exist.
I searched for the module on PyPi, and couldn't find it in the website neither.
I'm working straight out of the AWS Cloud9 IDE, using the Python CDK v2.
Any suggestions on how I could debug this would be very appreciated.

```Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from cdk_workshop.cdk_workshop_stack import CdkWorkshopStack
  File "/home/ec2-user/environment/cdk_workshop/cdk_workshop/cdk_workshop_stack.py", line 8, in <module>
    from .hitcounter import HitCounter
ModuleNotFoundError: No module named 'cdk_workshop.hitcounter'

Subprocess exited with error 1

### Expected Behavior

For the ``HitCounter module`` to be imported into the ``app.py`` file.

### Current Behavior

```
~/environment/cdk_workshop (master) $ cdk deploy
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from cdk_workshop.cdk_workshop_stack import CdkWorkshopStack
  File "/home/ec2-user/environment/cdk_workshop/cdk_workshop/cdk_workshop_stack.py", line 8, in <module>
    from .hitcounter import HitCounter
ModuleNotFoundError: No module named 'cdk_workshop.hitcounter'
Subprocess exited with error 1

### Reproduction Steps

See code snippet above

### CDK CLI Version

2

### Section

Write Constructs, Define the Hit Counter API

### Browser

Chrome

### Language

Python

**Comment by stefanfreitag** [comment]
Hi @Amanda-Ruzza,
the hitcounter is something you set up as part of the CDK workshop. So no need to search on PyPi :)
I can successfully run a cdk synth.

Here my `cdk_workshop_stack.py`, the import of the `hitcounter` is similar to your setup also on line 8. 
![image](https://user-images.githubusercontent.com/10981698/221374568-1355f663-9977-46df-bb27-e35e47fc8156.png)

The directory structure is as follows

![image](https://user-images.githubusercontent.com/10981698/221374642-5207f73a-4a69-41da-89d1-feac1fedc754.png)


I played a bit around and I got also your error message after renaming `hitcounter.py` to something else (here ` hitcounter2.py`).
![image](https://user-images.githubusercontent.com/10981698/221374843-42cdd00f-e86d-402b-be57-285a007ea279.png)

Could you provide details on the setup of your project (file/ directory structure)?

Cheers,
Stefan

**Comment by peterwoodworth** [comment]
Hey @Amanda-Ruzza, the comment that @stefanfreitag left was helpful. The hitcounter module is created as part of this project - make sure that you created the hitcounter module in the right file and folder and that you're importing it from the right location.

If you're still running into issues, please share your project file structure, and the contents of the hitcounter file as well as the files you are trying to implement the hitcounter module.

**Comment by Amanda-Ruzza** [comment]
Got it, thank you for the support. I was following the AWS Workshop using the Cloud9 IDE on my sandbox account which doesn't exist anymore, however, I'll try it out on my local environment.
