### ISSUE TITLE
Simple markdown typo in the doc

### ISSUE THREAD

**Issue by phasetr** [aws-samples/aws-cdk-intro-workshop#881]
### Describe the bug

The line 6 in [the file](https://github.com/aws-samples/aws-cdk-intro-workshop/edit/master/workshop/content/japanese/15-prerequisites/900-go.md), we have a wrong format for a link.

### Expected Behavior

- Now (a wrong format): `(go.dev)[https://go.dev/]`
- Expected: `[go.dev](https://go.dev/)`

### Current Behavior

We do not have a proper anchor.

### Reproduction Steps

Just open the page in the workshop site.

**Comment by stefanfreitag** [comment]
Seems to be an easy fix for english and japanese language. If there are no objections, I will try to come up with a PR.
