### ISSUE TITLE
npm run watch does not trigger an error for unused variable

### ISSUE THREAD

**Issue by javydekoning** [aws-samples/aws-cdk-intro-workshop#92]
### What is the problem?

https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html

**Mentions this:**
_Once you save cdk-workshop-stack.ts, you should see an error message in the npm run watch window that hello is declared but never use. Cool huh?_ 

Which is no longer accurate. IDE will still give this feedback though.

**Comment by NGL321** [comment]
Good catch! I'll put in a PR to fix this shortly
