### ISSUE TITLE
Syntax issue with the hello_stack.py provided in HitCounter Example

### ISSUE THREAD

**Issue by Nandini08** [aws-samples/aws-cdk-intro-workshop#93]
### What is the problem?
The code has syntax issues

### Reproduction Steps

$ cdk deploy hello-cdk-1

Traceback (most recent call last):
  File "app.py", line 5, in <module>
from aws_cdk import(core, aws_lambda as _lambda, aws_dynamodb as ddb, core, )
    from hello.hello_stack import MyStack
  File "/root/cdk-workshop/hello/hello_stack.py", line 3, in <module>
    from hitcounter import HitCounter
ModuleNotFoundError: No module named 'hitcounter'

Current code : 
from hitcounter import HitCounter

Expected code:
from .hitcounter import HitCounter

$ cdk diff hello-cdk-1
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    MyStack(app, "hello-cdk-1", env={'region': 'us-east-2'})
  File "/usr/local/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/root/cdk-workshop/hello/hello_stack.py", line 14, in __init__
    apigw.LambdaRestApi(self, 'APIEndpoint',handler=hello_with_counter.handler)
AttributeError: 'HitCounter' object has no attribute 'handler'

Current code : 
apigw.LambdaRestApi(self, 'Endpoint',handler=hello_with_counter.handler,)

Expected code:
apigw.LambdaRestApi(self, 'Endpoint',handler=hello_with_counter._handler,)

**Comment by victormwenda** [comment]
Just **putting aside** the changes to make on code _for those who do not have patience to read the whole doc!_

Current code :
`apigw.LambdaRestApi(self, 'Endpoint',handler=hello_with_counter.handler,)`

Expected code:
`apigw.LambdaRestApi(self, 'Endpoint',handler=hello_with_counter._handler,)`
