### ISSUE TITLE
[go] assertions.Template_FromStack of latest cdk has 2nd parameter.

### ISSUE THREAD

**Issue by turutcrane** [aws-samples/aws-cdk-intro-workshop#953]
### Describe the bug

In Go, assertions.Template_FromStack of latest cdk has 2nd parameter templateParsingOptions.
Original Go sample codes are based on v2.38.1.
So, code samles do not work against latest cdk.

 

### Expected Behavior

Sample codes work fine.

### Current Behavior

Sample codes are not compiled with latest go cdk sdk.

### Reproduction Steps

go vet .

### CDK CLI Version

 2.69.0 (build 60a5b2a)

### Language

Go

**Comment by peterwoodworth** [comment]
Thanks for reporting this and submitting a PR to go with it!
