### ISSUE TITLE
AWS CDK Python Workshop (sample-app) Broken & Out of Sync

### ISSUE THREAD

**Issue by calvincloutier** [aws-samples/aws-cdk-intro-workshop#98]
### What is the problem?
I am new to the CDK, so I figured following the workshop at cdkworkshop.com would be my best bet to learning how to use it. I tried to follow the python tutorial, but it is so out of sync that it is unusable at this point. There are syntax errors that get created by following the steps provided, and even when I came up with workarounds to avoid those, the cdk will fail to synth because of an error in the aws-cdk codebase.

### Reproduction Steps
The first issue I noticed is with the naming of the project directory as recommended by the tutorial. It says to do it like so:
<img width="1074" alt="Screen Shot 2019-12-03 at 11 04 40 AM" src="https://user-images.githubusercontent.com/55766525/70077236-09c78500-15c6-11ea-8037-37e6dff5fe14.png">

By following this step, I am able to initialize the sample-app, start the created virtualenv and install the requirements, but once I get to the point where I should be able to run `cdk synth`, it fails because of a syntax error in the code:
<img width="707" alt="Screen Shot 2019-12-03 at 11 06 58 AM" src="https://user-images.githubusercontent.com/55766525/70077714-f7018000-15c6-11ea-862a-5deaf82536b8.png">

Since this is directly due to the directory being created with a hyphen, my simple suggestion here would be to rename the directory in the workshop (eg. cdkWorkshop, cdk_workshop, cdkworkshop, etc.).

I then tried to restart the workshop with a new directory name (cdkws). I was able to get to the same spot in the tutorial, at which point I found multiple discrepancies in what I had via the sample-app vs. what was on the workshop site.

1. app.py
From the workshop:
<img width="1033" alt="Screen Shot 2019-12-03 at 12 28 36 PM" src="https://user-images.githubusercontent.com/55766525/70078630-a4c15e80-15c8-11ea-95b4-370f242c0d84.png">
From the downloaded sample-app:
<img width="494" alt="Screen Shot 2019-12-03 at 12 28 10 PM" src="https://user-images.githubusercontent.com/55766525/70078692-c589b400-15c8-11ea-9b2f-58d8cddc7967.png">

The naming difference is fine (it looks as though it used to always default to 'hello' for the stack code and it now is based on directory name), but a whole stack is missing in the sample-app?

2. xx_stack.py
workshop:
<img width="1035" alt="Screen Shot 2019-12-03 at 11 10 59 AM" src="https://user-images.githubusercontent.com/55766525/70079001-7001d700-15c9-11ea-9ff5-bb9a8006903b.png">
sample-app:
<img width="579" alt="Screen Shot 2019-12-03 at 12 34 50 PM" src="https://user-images.githubusercontent.com/55766525/70079023-7f812000-15c9-11ea-90b8-1e92a86de68a.png">
HelloConstruct is not even imported in the sample-app (nor is it a file in anywhere in the project), and there's multiple missing lines of code.
<img width="773" alt="Screen Shot 2019-12-03 at 12 41 00 PM" src="https://user-images.githubusercontent.com/55766525/70079402-4a290200-15ca-11ea-9ada-76c53e904d85.png">

Even ignoring these issues, when I try to run `cdk synth` or `cdk ls` to continue with the workshop, it fails, this time for another reason:
<img width="1297" alt="Screen Shot 2019-12-03 at 12 44 30 PM" src="https://user-images.githubusercontent.com/55766525/70079783-05ea3180-15cb-11ea-8801-6b8cacafaab4.png">
All 'cdk' commands, including running `pytest` fail with this same exact issue.

Any reason why this is so out of sync and broken? Are there expected updates to fix these issues? I would love to follow the tutorial but it's unusable at this point. I'm happy to provide more info if needed.

### Environment

  - **CDK CLI Version:** 1.18.0 (build bc924bc)
  - **Section:** Python Workshop/New Project
  - **Browser:** Chrome 78.0.3904.108
  - **Language:** Python 3.7.5

**Comment by calvincloutier** [comment]
I see that the `cdk` command issues have already been reported and are being investigated in [5187](https://github.com/aws/aws-cdk/issues/5187) and appear to be tied to the recent node upgrade to 13.2.0.

**Comment by NGL321** [comment]
Hi @calvincloutier,

I am **SO** sorry you went through this. I really appreciate the detailed and constructive issue submission. It appears that in our process of updating the workshop to include our new languages, we inadvertently deprecated it for Python. 
I will look into resolving this ASAP and get back to you on this issue once fixed.

In the interim, if you are familiar with any of the other languages and want to walk through the Workshop, we have done our best to make sure that the experience is directly parallel, so the understanding gained of the CDK should be equivalent.
Otherwise, hold tight and I will get a fix up.

Thank you again!
😸

**Comment by calvincloutier** [comment]
Hi @NGL321,

Thanks for the prompt reply. After reverting my node version from 13.2.0 -> 13.1.0, I was able to run all `cdk` commands as noted in issue 5187. I continued on with the workshop, and it turns out that the omitted lines I mentioned above were not critical to the rest of the workshop. I was able to finish the workshop and the rest of the documentation was very detailed.

So, while it still may be beneficial for the sample-app to mirror what is in the workshop, it was not by no means "unusable" as I had previously stated. I apologize if that came off abrasive.

Appreciate all the work you do and thanks again! 😃

**Comment by brettberginbc** [comment]
@calvincloutier Great write up, and thanks so much for the detail. I as well just started the workshop, and experienced the same issue you have described. Would you mind sharing the steps you used to downgrade node? I've tried using `n` to do this, but am still receiving the same error.

**Comment by calvincloutier** [comment]
@brettberginbc I actually deprecated my version to 12.13.1, which is the "stable" version according to `n`. If you just run `n stable` it should install it.

Make sure to note the directory that it installs to after it completes, then make sure your terminal is using that newly installed version (`which node` if you're not on Windows). If not, it may not be in your path.

Hope that helps!

**Comment by brettberginbc** [comment]
Worked great! Thanks for the help.

**Comment by NGL321** [comment]
@calvincloutier We strive for excellence, so really dont hesitate to comment if something is off or frustrating!

I should be pushing a fix to resolve this within a couple hours.
